---
title: "Figure 7 - CD1d and SFR expression in human and murine thymus"
author: "Salomé Carcy"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true

---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  fig.width = 5,
  fig.height = 5,
  warning = FALSE,
  message = FALSE,
  attr.output='style="max-height: 300px;"',
  root.dir = "~/Projects/HumanThymusProject/"
)
```




# IMPORT

## Import librairies
```{r import-librairies}
library(ggplot2)
library(RColorBrewer)
library(cowplot)
library(tidyverse)
library(dplyr)
library(Seurat)
library(SCpubr)
library(patchwork)

setwd("~/Projects/HumanThymusProject/")
source("~/Projects/HumanThymusProject/scripts/colors_universal.R")
```


## Import data
The human and murine thymic seurat objects come from the Thymic Atlas generated by [Park et al.](https://www.science.org/doi/10.1126/science.aay3224). See script [download_park_thymic_atlas.Rmd](...) for how we obtained these seurat objects with appropriate metadata.
```{r import-data}
seur.human <- readRDS("~/Projects/HumanThymusProject/data/human-thymus/HumanData_16_ParkIntegration/park_full_seu_gene_names.rds")
seur_metadata <- read.csv("~/Projects/HumanThymusProject/data/human-thymus/HumanData_16_ParkIntegration/park_fullmetadata.csv")

seur.mouse <- readRDS("~/Projects/HumanThymusProject/data/raw_data/mouse_data/thymus_Park/park_seu_mouse.rds")

# Incorporate metadata in seurat object
table(seur_metadata$index == rownames(seur.human@meta.data), useNA="ifany")
seur.human@meta.data <- cbind(seur.human@meta.data, seur_metadata)
```




# FUNCTIONS
```{r define-functions}

```




# ANALYSIS

## Analysis 1
```{r analysis-1}

```


## Analysis 2
```{r analysis-2}

```

## Analysis 1
```{r analysis-1}

```


## Analysis 2
```{r analysis-2}

```

## Analysis 3
```{r analysis-3}

```


## Analysis 4
```{r analysis-4}

```




# SESSION INFO
```{r}
sessionInfo()
```


