---
title: "Prepare data to run pyMetaNeighbor across species"
author: "Salomé Carcy"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  fig.width = 5,
  fig.height = 5,
  warning = FALSE,
  message = FALSE,
  attr.output='style="max-height: 300px;"',
  root.dir = "~/Projects/HumanThymusProject/"
)
```


# IMPORT

## Import librairies
```{r import-librairies}
library(ggplot2)
library(tidyverse)
library(dplyr)
library(Seurat)
library(SCpubr)

setwd("~/Projects/HumanThymusProject/")
source("~/Projects/HumanThymusProject/scripts/colors_universal.R")
```

## Import data
```{r import-data}
# human
seur.hu <- list(
  "nkt"=readRDS("./data_github/seurat_objects_thymus/seurat_thymus_inkt.rds"),
  "mait"=readRDS("./data_github/seurat_objects_thymus/seurat_thymus_mait.rds"),
  "gdt"=readRDS("./data_github/seurat_objects_thymus/seurat_thymus_gdt.rds")
)
DimPlot(seur.hu$nkt,  group.by="clusters_per_lineage", cols=cols_thym_nkt)
DimPlot(seur.hu$mait, group.by="clusters_per_lineage", cols=cols_thym_mait)
DimPlot(seur.hu$gdt,  group.by="clusters_per_lineage", cols=cols_thym_gdt)

# mouse
seur.ms <- readRDS("./data_geo/seurat_objects/seurat_mouse_integrated_object_23_12_02.rds")
DimPlot(seur.ms,  group.by="clusters_annotation")
```




# FUNCTIONS
```{r define-functions}

```




# ANALYSIS

## Analysis 1
```{r analysis-1}

```


## Analysis 2
```{r analysis-2}

```

## Analysis 1
```{r analysis-1}

```


## Analysis 2
```{r analysis-2}

```

## Analysis 3
```{r analysis-3}

```


## Analysis 4
```{r analysis-4}

```




# SESSION INFO
```{r}
sessionInfo()
```


