---
title: "Human T cell data - Correlation gene expression btw clusters of each T cell lineage"
output:
  html_document:
    df_print: paged
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```




## 1. IMPORT

### 1.1. Import librairies & data
```{r import-librairies, message=FALSE}
library(ggplot2)
library(cowplot)
library(tidyverse)
library(dplyr)
library(Seurat)
library(RColorBrewer)
library(harmony)
library(corrplot)
library(pals)
library(VennDiagram)
library(ggalluvial)
# library(SingleCellExperiment)
```

```{r import-data, fig.height=8, fig.width=8}
# Import seurat object
seur <- readRDS("~/Projects/HumanThymusProject/data/raw_data/human_data/seurat_filtered_harmony_02_15_23.RDS") # removed low-quality cells

# Sanity check
print(seur) # 78,607 cells
cols_integrated <- c("0" = "#f4c40f", "1" = "#b75347", "2" = "#d8443c", "3" = "#e09351", "4" = "#2b9b81", 
                     "5" = "#421401", "6" = "#92c051", "7" = "#9f5691", "8" = "#17154f", "9" = "#74c8c3", 
                     "10" = "#5a97c1", "11" = "gold", "12" = "#a40000", "13" = "#72bcd5", "14" = "grey50",
                     "15" = "orange", "16" = "blueviolet", "17" = "#0a2e57", "18" = "#bdbdbd")
SCpubr::do_DimPlot(seur, 
                   group.by = "new_clusters",
                   label=T,
                   label.color="black",
                   legend.position = "none",
                   repel=T,
                   colors.use=cols_integrated,
                   font.size = 24)

# Get raw object?
counts <- seur@assays$RNA@counts
metadata <- seur@meta.data
seur.filt <- CreateSeuratObject(counts=counts, meta.data = metadata)

# Quick visualization
# DimPlot(seur.human, reduction="UMAP_50", group.by="new_clusters") +
#   scale_color_manual(values=colorRampPalette(brewer.pal(12,"Paired"))(18))
```

```{r import-data2, eval=FALSE, include=FALSE, fig.width=20, fig.height=10}
seur.thycd4  <- readRDS("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/seurat_thymus-CD4_2023-02-27.rds")
seur.cd8  <- readRDS("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/seurat_thymus-CD8_2023-02-27.rds")
seur.nkt  <- readRDS("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/seurat_thymus-NKT_2023-02-27.rds")
seur.mait <- readRDS("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/seurat_thymus-MAIT_2023-02-27.rds")
seur.gd   <- readRDS("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/seurat_thymus-GDT_2023-02-27.rds")

effectorness_genes <- c("HOPX", "GZMB", "GZMK", "ZEB2", "NKG7", "GNLY", "TBX21", "EOMES", "TYROBP", "PRF1", 
                        "CCL4", "CCL5", "KLRB1", "GZMH", "GZMA", "KLRD1", "CST7", "KLF6", "CXCR4")
naive_genes <- c("SATB1", "TCF7", "LEF1", "CCR7", "SELL", "MYC", "EIF3E", "SOX4", "ID3", "BACH2",
                 "PTPRC", "IL7R", "IL2RG")
egress_genes <- c("KLF2", "CORO1A", "CCR7", "CXCR4", "CXCR6", "FOXO1", "CXCR3", "S1PR1", "S1PR4", "S100A4", "S100A6", "EMP3")

# Calculate the module scores and add them to the Seurat object
seur.thycd4 <- AddModuleScore(object = seur.thycd4, assay = "RNA", features = list("effector"=effectorness_genes, "naive"=naive_genes, "egress"=egress_genes), name=c("effector", "naive", "egress"))
seur.cd8 <- AddModuleScore(object = seur.cd8, assay = "RNA", features = list("effector"=effectorness_genes, "naive"=naive_genes, "egress"=egress_genes), name=c("effector", "naive", "egress"))
seur.nkt <- AddModuleScore(object = seur.nkt, assay = "RNA", features = list("effector"=effectorness_genes, "naive"=naive_genes, "egress"=egress_genes), name=c("effector", "naive", "egress"))
seur.mait <- AddModuleScore(object = seur.mait, assay = "RNA", features = list("effector"=effectorness_genes, "naive"=naive_genes, "egress"=egress_genes), name=c("effector", "naive", "egress"))
seur.gd <- AddModuleScore(object = seur.gd, assay = "RNA", features = list("effector"=effectorness_genes, "naive"=naive_genes, "egress"=egress_genes), name=c("effector", "naive", "egress"))
seur <- AddModuleScore(object = seur, assay = "RNA", features = list("eff"=effectorness_genes, "naiv"=naive_genes, "egr"=egress_genes), name=c("eff", "naiv", "egr"))

SCpubr::do_FeaturePlot(seur, 
                       features=c("eff1", "naiv2", "egr3"),
                       viridis_color_map = "A",
                       ncol=3,
                       order=T,
                   # group.by = "new_clusters",
                   # label=T,
                   # label.color="black",
                   # legend.position = "none",
                   # repel=T,
                   # colors.use=cols_integrated,
                   font.size = 24)
ggsave("~/Projects/HumanThymusProject/data/human-thymus/HumanData_14_CCR9-CCR7-plots/genescores_integrated.jpeg", width=30, height=15)

# VlnPlot(seur.thycd4, features=c("effector1", "naive2"), group.by="cell_annot")
# VlnPlot(seur.cd8, features=c("effector1", "naive2"), group.by="cell_annot")
# VlnPlot(seur.nkt, features=c("effector1", "naive2"), group.by="cell_annot")
# VlnPlot(seur.mait, features=c("effector1", "naive2"), group.by="cell_annot")
# VlnPlot(seur.gd, features=c("effector1", "naive2"), group.by="cell_annot")

# Put together into DF
df <- data.frame(rbind(seur.thycd4@meta.data[,c("cell.ident", "cell_annot", "effector1", "naive2", "egress3")],
                       seur.cd8@meta.data[,   c("cell.ident", "cell_annot", "effector1", "naive2", "egress3")],
                       seur.nkt@meta.data[,   c("cell.ident", "cell_annot", "effector1", "naive2", "egress3")],
                       seur.thycd4@meta.data[,c("cell.ident", "cell_annot", "effector1", "naive2", "egress3")],
                       seur.mait@meta.data[,  c("cell.ident", "cell_annot", "effector1", "naive2", "egress3")],
                       seur.gd@meta.data[,    c("cell.ident", "cell_annot", "effector1", "naive2", "egress3")])) %>%
  rename(effector=effector1, naive=naive2, egress=egress3)

# colors
cols_cd4 <- c("#c7e9c0", "#238b45", "#edf8e9", "#41ab5d", "#74c476","#005a32", "#a1d99b")
names(cols_cd4) <- unique(seur.thycd4$cell_annot)
cols_cd8 <- c("#f768a1", "#f1eef6", "#c994c7", "#fa9fb5", "#df65b0","#d4b9da")
names(cols_cd8) <- unique(seur.cd8$cell_annot)
cols_mait <- c("#2171b5", "#6baed6", "#9ecae1", "#deebf7", "#c6dbef", "#f7fbff", "#4292c6")
names(cols_mait) <- unique(seur.mait$cell_annot)
cols_nkt <- c("#9e9ac8", "#f2f0f7", "#cbc9e2", "#54278f", "#756bb1")
names(cols_nkt) <- unique(seur.nkt$cell_annot)
cols_gdt <- c("#74a9cf", "#3690c0", "#045a8d", "#023858", "#0570b0", "#a6bddb")
names(cols_gdt) <- unique(seur.gd$cell_annot)

cols <- c(cols_cd4, cols_cd8, cols_mait, cols_nkt, cols_gdt)

clusters_levels=c("thyCD4_ISP", "thyCD4_DPp", "thyCD4_DPq", "thyCD4_ccr9", "thyCD4_ccr7", "thyCD4_Tagonist", "thyCD4_Treg",
                  "thyCD8_DP", "thyCD8_ccr9", "thyCD8_idk", "thyCD8_ccr7", "thyCD8_cd8aa1", "thyCD8_cd8aa2",
                  "thyMAIT_DP", "thyMAIT_cd8aa", "thyMAIT_ccr9", "thyMAIT_idk", "thyMAIT_ccr7", "thyMAIT_IFNsig", "thyMAIT_effector",
                  "thyNKT_cd8aa", "thyNKT_ccr9", "thyNKT_ccr7", "thyNKT_effFOSJUN", "thyNKT_effector",
                  "thyGDT_DP", "thyGDT_immat_cycl", "thyGDT_immat", "thyGDT_ccr9", "thyGDT_IFNsig", "thyGDT_effector")

# VlnPlot
ggplot(df, aes(x=factor(cell_annot, level=clusters_levels), y=effector, fill=cell_annot)) +
  geom_violin(color="black", scale="width")+
  geom_jitter(size=0.2, width=0.1)+
  scale_fill_manual(values=cols)+
  labs(x="", y="Effector gene score", title="Effectorness score")+
  geom_vline(xintercept=c(7.5, 13.5,20.5,25.5), linetype="dashed", color="darkgrey")+
  theme_cowplot() +
  theme(axis.text.x = element_text(angle=45, hjust=1),
        plot.title = element_text(hjust=0.5),
        legend.position="none")
# ggsave("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/score_effector.jpeg", width=15, height=7)

ggplot(df, aes(x=factor(cell_annot, level=clusters_levels), y=naive, fill=cell_annot)) +
  geom_violin(color="black", scale="width")+
  geom_jitter(size=0.2, width=0.1)+
  scale_fill_manual(values=cols)+
  labs(x="", y="Naive gene score", title="Naiveness score")+
  geom_vline(xintercept=c(7.5, 13.5,20.5,25.5), linetype="dashed", color="darkgrey")+
  theme_cowplot() +
  theme(axis.text.x = element_text(angle=45, hjust=1),
        plot.title = element_text(hjust=0.5),
        legend.position="none")
# ggsave("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/score_naive.jpeg", width=15, height=7)

ggplot(df, aes(x=factor(cell_annot, level=clusters_levels), y=egress, fill=cell_annot)) +
  geom_violin(color="black", scale="width")+
  geom_jitter(size=0.2, width=0.1)+
  scale_fill_manual(values=cols)+
  # scale_color_manual(values=cols)+
  labs(x="", y="Egress gene score", title="Egress score")+
  geom_vline(xintercept=c(7.5, 13.5,20.5,25.5), linetype="dashed", color="darkgrey")+
  theme_cowplot() +
  theme(axis.text.x = element_text(angle=45, hjust=1),
        plot.title = element_text(hjust=0.5),
        legend.position="none")
# ggsave("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/score_egress.jpeg", width=15, height=7)
```




## 2. PREPROCESSING

### 2.1. Functions

```{r preprocessing1}
# Preprocessing
preprocess <- function(seurobj, ndim, res, celltype, approxPCA=FALSE){
  print(seurobj)
  cat("Cells:", unique(seurobj$group.ident), "\n")
  
  print("Normalize")
  seurobj <- NormalizeData(seurobj)
  print("HVG")
  if(length(VariableFeatures(seurobj))==0){
      print("-> Compute 2000 HVGs")
      seurobj <- FindVariableFeatures(seurobj, selection.method="vst", nfeatures=2000)
  } else if(length(VariableFeatures(seurobj))>0){
    print(paste0("-> ", length(VariableFeatures(seurobj)), " HVGs already set in object"))
  }
  print("Scale")
  seurobj <- ScaleData(seurobj)
  print("PCA")
  seurobj <- RunPCA(seurobj, npcs=50, verbose=FALSE, approx=approxPCA)
  print("Harmony")
  seurobj <- RunHarmony(seurobj, reduction = "pca", max.iter.harmony=30, group.by.vars = c("Method", "Batch"))
  # DimPlot(seurobj, reduction="pca", group.by="Batch") | DimPlot(seurobj, reduction="harmony", group.by="Batch")
  # DimPlot(seurobj, reduction="pca", group.by="Method") | DimPlot(seurobj, reduction="harmony", group.by="Method")
  print(ElbowPlot(seurobj, ndims=50, reduction="harmony"))
  print("UMAP")
  seurobj <- RunUMAP(seurobj, reduction = "harmony", dims = 1:ndim, n.neighbors=50, reduction.key = "UMAP50_")
  print("Cluster")
  seurobj <- FindNeighbors(seurobj, reduction = "harmony", dims = 1:ndim)
  seurobj <- FindClusters(seurobj, resolution = res, random.seed = 0)
  
  # Visualization sanity check
  print(DimPlot(seurobj, reduction = "umap", group.by="seurat_clusters", label = TRUE, repel = TRUE)+
    scale_color_manual(values=colorRampPalette(brewer.pal(12,"Paired"))(18)) +
    labs(title=celltype))
  
  return(seurobj)
}

# Sanity check
# test <- preprocess(seur.filt, res=1, celltype="all") # verified on 01.24
```


### 2.2. CD4 T cells

#### 2.2.1. CD4 Thymocytes
```{r preprocessing-cd4-thymus}
# Run preprocessing
# unique(seur.filt$group.ident)
seur.thycd4 <- preprocess(seurobj = subset(seur.filt, subset=group.ident=="CD4_Thymus"),  celltype = "CD4thy", ndim=10, res=0.2)

# Annotate
# Idents(seur.thycd4) <- "cell_annot"
# markers <- FindAllMarkers(seur.thycd4, only.pos=TRUE, min.pct=0.25, logfc.threshold=0.5) %>%
#   group_by(cluster) %>%
#   slice_max(n=5, order_by=avg_log2FC)

seur.thycd4@meta.data$cell_annot <- case_when(
  seur.thycd4@meta.data$seurat_clusters == 0 ~ "thyCD4_ccr9",
  seur.thycd4@meta.data$seurat_clusters == 1 ~ "thyCD4_ccr7",
  seur.thycd4@meta.data$seurat_clusters == 2 ~ "thyCD4_ISP",
  seur.thycd4@meta.data$seurat_clusters == 3 ~ "thyCD4_Treg",
  seur.thycd4@meta.data$seurat_clusters == 4 ~ "thyCD4_DPp",
  seur.thycd4@meta.data$seurat_clusters == 5 ~ "thyCD4_Tagonist",
  seur.thycd4@meta.data$seurat_clusters == 6 ~ "thyCD4_DPq"
)
# saveRDS(seur.thycd4, "~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/seurat_thymus-CD4_2023-02-27.rds")

ggpubr::ggarrange(DimPlot(seur.thycd4, group.by="cell_annot", label=T, repel=T) +
                    theme(legend.position="none") + labs(title="Thymic CD4"),
                  DotPlot(seur.thycd4, features=unique(c("CD4", "CD8A", "CD8B", "RAG1", markers$gene))) +
                    labs(x="", y="") + theme(axis.text.x=element_text(angle=90, hjust=1, vjust=0.5, size=7)),
                  ncol=2, widths = c(1.2,2))
# ggsave("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_CorrelationGEbtwTlineages/umap_thyCD4.jpeg", width=12, height=5)

# SCpubr
cols_cd4 <- c("#c7e9c0", "#238b45", "#edf8e9", "#41ab5d", "#74c476","#005a32", "#a1d99b")
names(cols_cd4) <- unique(seur.thycd4$cell_annot)
SCpubr::do_DimPlot(seur.thycd4, 
                   group.by = "cell_annot",
                   label=T,
                   label.color="black",
                   legend.position = "none",
                   repel=T,
                   colors.use=cols_cd4,
                   font.size = 24)
# ggsave("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/scpubr_cd4.jpeg", width=6, height=6)
```

```{r preprocessing-cd4-thymus2, fig.width=24, fig.height=8}
# Import object if necessary
# seur.thycd4 <- readRDS("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/seurat_thymus-CD4_2023-02-27.rds")

# Add thymic CD4 clusters to integrated object
table(rownames(seur@meta.data[seur@meta.data$group.ident=="CD4_Thymus",]) == rownames(seur.thycd4@meta.data)) # check rownames are in same order
seur@meta.data[seur@meta.data$group.ident=="CD4_Thymus", "clusters_thyCD4"] <- seur.thycd4@meta.data$cell_annot
table(seur@meta.data[,c("group.ident", "clusters_thyCD4")], useNA="ifany")


# Plot newly-assigned clusters & clusters from integrated object
cols_cd4 <- c("#c7e9c0", "#238b45", "#edf8e9", "#41ab5d", "#74c476","#005a32", "#a1d99b")
names(cols_cd4) <- unique(seur.thycd4$cell_annot)
SCpubr::do_DimPlot(seur.thycd4, 
                   group.by = "cell_annot",
                   label=T,
                   label.color="black",
                   legend.position = "none",
                   repel=T,
                   colors.use=cols_cd4,
                   plot.title="CD4 thymocyte clusters",
                   font.size = 24) |
  SCpubr::do_DimPlot(seur.thycd4, 
                   group.by = "new_clusters",
                   label=T,
                   label.color="black",
                   legend.position = "none",
                   repel=T,
                   colors.use=cols_integrated,
                   plot.title="Integrated object clusters",
                   font.size = 24) |
  SCpubr::do_DimPlot(seur, 
                     group.by = "clusters_thyCD4",
                     na.value=adjustcolor("grey90", alpha.f = 0.5),
                     border.size=1,
                     label=T,
                     label.color="black ",
                     legend.position = "none",
                     repel=T,
                     colors.use=cols_cd4,
                   plot.title="CD4 thymocyte clusters on integrated object",
                   font.size = 24)
# ggsave("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/cd4_thy_overlap.jpeg", width=24, height=8)


# Ggalluvial
test <- seur@meta.data %>%
  as_tibble() %>%
  filter(Tissue=="Thymus") %>%
  group_by(new_clusters, clusters_thyCD4) %>%
  summarise(ncells=n()) %>%
  filter(!is.na(clusters_thyCD4)) %>%
  rename("integrated_clusters" = "new_clusters",
         "cd4_clusters" = "clusters_thyCD4")

ggplot(test, aes(y=ncells, axis1=integrated_clusters, axis2=cd4_clusters)) +
  geom_alluvium(aes(fill=integrated_clusters), width = 1/12, lode.guidance="frontback") +
  geom_stratum(width = 1/12, fill = "black", color = "grey") +
  geom_label(stat = "stratum", aes(label = after_stat(stratum))) +
  scale_x_discrete(limits = c("integrated_clusters", "thyCD4_clusters"), expand = c(.05, .05)) +
  scale_fill_manual(values=cols_integrated) +
  labs(title="Comparison thymic CD4 cluster assignment", y="#cells")
# ggsave("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/cd4_thy_overlap2.jpeg", width=10, height=8)

```

#### 2.2.2. CD4 cells overall
```{r preprocessing-cd4-all}
# Run preprocessing
# unique(seur.filt$group.ident)
seur.cd4 <- preprocess(seurobj = subset(seur.filt, subset=cell.ident=="CD4"),  celltype = "CD4", ndim=10, res=0.2)
DimPlot(seur.cd4) |
  DimPlot(seur.cd4, group.by="Tissue")


# Annotate
# Idents(seur.cd4) <- "cell_annot"
# markers <- FindAllMarkers(seur.cd4, only.pos=TRUE, min.pct=0.25, logfc.threshold=0.5) %>%
#   group_by(cluster) %>%
#   slice_max(n=5, order_by=avg_log2FC)

seur.cd4@meta.data$cell_annot <- case_when(
  seur.cd4@meta.data$seurat_clusters == 0 ~ "thyCD4_ccr9",
  seur.cd4@meta.data$seurat_clusters == 1 ~ "thyCD4_ccr7",
  seur.cd4@meta.data$seurat_clusters == 2 ~ "thyCD4_ISP",
  seur.cd4@meta.data$seurat_clusters == 3 ~ "thyCD4_Treg",
  seur.cd4@meta.data$seurat_clusters == 4 ~ "thyCD4_DPp",
  seur.cd4@meta.data$seurat_clusters == 5 ~ "thyCD4_Tagonist",
  seur.cd4@meta.data$seurat_clusters == 6 ~ "thyCD4_DPq"
)
# saveRDS(seur.cd4, "~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/seurat_thymus-CD4_2023-02-27.rds")

ggpubr::ggarrange(DimPlot(seur.cd4, group.by="cell_annot", label=T, repel=T) +
                    theme(legend.position="none") + labs(title="Thymic CD4"),
                  DotPlot(seur.cd4, features=unique(c("CD4", "CD8A", "CD8B", "RAG1", markers$gene))) +
                    labs(x="", y="") + theme(axis.text.x=element_text(angle=90, hjust=1, vjust=0.5, size=7)),
                  ncol=2, widths = c(1.2,2))
# ggsave("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_CorrelationGEbtwTlineages/umap_thyCD4.jpeg", width=12, height=5)

# SCpubr
cols_cd4 <- c("#c7e9c0", "#238b45", "#edf8e9", "#41ab5d", "#74c476","#005a32", "#a1d99b")
names(cols_cd4) <- unique(seur.cd4$cell_annot)
SCpubr::do_DimPlot(seur.cd4, 
                   group.by = "cell_annot",
                   label=T,
                   label.color="black",
                   legend.position = "none",
                   repel=T,
                   colors.use=cols_cd4,
                   font.size = 24)
# ggsave("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/scpubr_cd4.jpeg", width=6, height=6)
```



### 2.3. CD8 T cells
```{r preprocessing-cd8-thymus}
seur.cd8 <- preprocess(seurobj = subset(seur.filt, subset=group.ident=="CD8_Thymus"),  celltype = "CD8thy", ndim=10, res=0.2)

# Annotate
# Idents(seur.cd8) <- "cell_annot"
# markers <- FindAllMarkers(seur.cd8, only.pos=TRUE, min.pct=0.25, logfc.threshold=0.5) %>%
#   group_by(cluster) %>%
#   slice_max(n=10, order_by=avg_log2FC)

seur.cd8@meta.data$cell_annot <- case_when(
  seur.cd8@meta.data$seurat_clusters == 0 ~ "thyCD8_ccr7",
  seur.cd8@meta.data$seurat_clusters == 1 ~ "thyCD8_ccr9", # ccr9?
  seur.cd8@meta.data$seurat_clusters == 2 ~ "thyCD8_cd8aa1",
  seur.cd8@meta.data$seurat_clusters == 3 ~ "thyCD8_idk",
  seur.cd8@meta.data$seurat_clusters == 4 ~ "thyCD8_cd8aa2",
  seur.cd8@meta.data$seurat_clusters == 5 ~ "thyCD8_DP"
)
# saveRDS(seur.cd8, "~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/seurat_thymus-CD8_2023-02-27.rds")

ggpubr::ggarrange(DimPlot(seur.cd8, group.by="cell_annot", label=T, repel=T) +
                    theme(legend.position="none") + labs(title="Thymic CD8"),
                  DotPlot(seur.cd8, features=unique(c("CD4", "CD8A", "CD8B", "RAG1", markers$gene))) +
                    labs(x="", y="") + theme(axis.text.x=element_text(angle=90, hjust=1, vjust=0.5, size=7)),
                  ncol=2, widths = c(1,2))
# ggsave("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_CorrelationGEbtwTlineages/umap_thyCD8.jpeg", width=15, height=5)

# SCpubr
cols_cd8 <- c("#f768a1", "#f1eef6", "#c994c7", "#fa9fb5", "#df65b0","#d4b9da")
names(cols_cd8) <- unique(seur.cd8$cell_annot)
SCpubr::do_DimPlot(seur.cd8, 
                   group.by = "cell_annot",
                   label=T,
                   label.color="black",
                   legend.position = "none",
                   repel=T,
                   colors.use=cols_cd8,
                   font.size = 24)
# ggsave("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/scpubr_cd8.jpeg", width=6, height=6)

# Park gene signature
seur.cd8 <- readRDS("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/seurat_thymus-CD8_2023-02-27.rds")
park.markers <- read.csv("~/Projects/HumanThymusProject/data/park_genesignatures.csv")
seur.cd8 <- AddModuleScore(seur.cd8, features=list("cd8aa1"=park.markers$CD8aa1, "cd8aa2"=park.markers$CD8aa2), name="cd8aa")
SCpubr::do_DimPlot(seur.cd8, 
                   group.by = "cell_annot",
                   label=T,
                   label.color="black",
                   legend.position = "none",
                   repel=T,
                   colors.use=cols_cd8,
                   font.size = 24) |
SCpubr::do_FeaturePlot(seur.cd8, 
                   features = "cd8aa1",
                   viridis_color_map = "A",
                   order=T,
                   font.size = 24) |
SCpubr::do_FeaturePlot(seur.cd8, 
                   features = "cd8aa2",
                   viridis_color_map = "A",
                   order=T,
                   font.size = 24)
ggsave("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/cd8aa_signatures.jpeg", width=18, height=6)
```

```{r preprocessing-cd8-thymus2, fig.width=24, fig.height=8}
# Import object if necessary
seur.thycd8 <- readRDS("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/seurat_thymus-CD8_2023-02-27.rds")

# Add thymic CD4 clusters to integrated object
table(rownames(seur@meta.data[seur@meta.data$group.ident=="CD8_Thymus",]) == rownames(seur.thycd8@meta.data)) # check rownames are in same order
seur@meta.data[seur@meta.data$group.ident=="CD8_Thymus", "clusters_thyCD8"] <- seur.thycd8@meta.data$cell_annot
table(seur@meta.data[,c("group.ident", "clusters_thyCD8")], useNA="ifany")


# Plot newly-assigned clusters & clusters from integrated object
cols_cd8 <- c("#f768a1", "#f1eef6", "#c994c7", "#fa9fb5", "#df65b0","#d4b9da")
names(cols_cd8) <- unique(seur.thycd8$cell_annot)
SCpubr::do_DimPlot(seur.thycd8, 
                   group.by = "cell_annot",
                   label=T,
                   label.color="black",
                   legend.position = "none",
                   repel=T,
                   colors.use=cols_cd8,
                   plot.title="CD8 thymocyte clusters",
                   font.size = 24) |
  SCpubr::do_DimPlot(seur.thycd8, 
                   group.by = "new_clusters",
                   label=T,
                   label.color="black",
                   legend.position = "none",
                   repel=T,
                   colors.use=cols_integrated,
                   plot.title="Integrated object clusters",
                   font.size = 24) |
  SCpubr::do_DimPlot(seur, 
                     group.by = "clusters_thyCD8",
                     na.value=adjustcolor("grey90", alpha.f = 0.5),
                     border.size=1,
                     label=T,
                     label.color="black",
                     legend.position = "none",
                     repel=T,
                     colors.use=cols_cd8,
                   plot.title="CD8 thymocyte clusters on integrated object",
                   font.size = 24)
# ggsave("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/cd8_thy_overlap.jpeg", width=24, height=8)
```





### 2.4. MAIT cells
```{r preprocessing-mait}
# Preprocess
seur.mait <- preprocess(seurobj = subset(seur.filt, subset=group.ident=="MAIT_Thymus"), celltype = "MAITthy", ndim=10, res=0.2)

# Annotate
# Idents(seur.thymait) <- "cell_annot"
# markers <- FindAllMarkers(seur.thymait, only.pos=TRUE, min.pct=0.25, logfc.threshold=0.5) %>%
#   group_by(cluster) %>%
#   slice_max(n=5, order_by=avg_log2FC)

# seur.thymait@meta.data$cell_annot <- case_when(
#   seur.thymait@meta.data$seurat_clusters == 0 ~ "thyMAIT_ccr9",
#   seur.thymait@meta.data$seurat_clusters == 1 ~ "thyMAIT_ccr7",
#   seur.thymait@meta.data$seurat_clusters == 2 ~ "thyMAIT_effector",
#   seur.thymait@meta.data$seurat_clusters == 3 ~ "thyMAIT_idk",
#   seur.thymait@meta.data$seurat_clusters == 4 ~ "thyMAIT_cd8aa",
#   seur.thymait@meta.data$seurat_clusters == 5 ~ "thyMAIT_DP",
#   seur.thymait@meta.data$seurat_clusters == 6 ~ "thyMAIT_IFNsig"
# )
seur.thymait@meta.data$cell_annot <- case_when(
  seur.thymait@meta.data$seurat_clusters == 0 ~ "MAIT_c2",
  seur.thymait@meta.data$seurat_clusters == 1 ~ "MAIT_c4",
  seur.thymait@meta.data$seurat_clusters == 2 ~ "MAIT_c6",
  seur.thymait@meta.data$seurat_clusters == 3 ~ "MAIT_c3",
  seur.thymait@meta.data$seurat_clusters == 4 ~ "MAIT_c1",
  seur.thymait@meta.data$seurat_clusters == 5 ~ "MAIT_c0",
  seur.thymait@meta.data$seurat_clusters == 6 ~ "MAIT_c5"
)
# saveRDS(seur.thymait, "~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/seurat_thymus-MAIT_2023-02-27.rds")

ggpubr::ggarrange(DimPlot(seur.thymait, group.by="cell_annot", label=T, repel=T) +
                    theme(legend.position="none") + labs(title="Thymic MAIT"),
                  DotPlot(seur.thymait, features=unique(c("CD4", "CD8A", "CD8B", "RAG1", markers$gene))) +
                    labs(x="", y="") + theme(axis.text.x=element_text(angle=90, hjust=1, vjust=0.5, size=7)),
                  ncol=2, widths = c(1.2,2))
# ggsave("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_CorrelationGEbtwTlineages/umap_thyMAIT.jpeg", width=12, height=5)


# SCpubr
cols_mait <- c("#2171b5", "#6baed6", "#9ecae1", "#deebf7", "#c6dbef", "#f7fbff", "#4292c6")
names(cols_mait) <- unique(seur.mait$cell_annot)
SCpubr::do_DimPlot(seur.mait, 
                   group.by = "cell_annot",
                   label=T,
                   label.color="black",
                   legend.position = "none",
                   repel=T,
                   colors.use=cols_mait,
                   font.size = 24)
# ggsave("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/scpubr_mait.jpeg", width=6, height=6)


# Markers MAIT
# markers.mait <- FindAllMarkers(seur.mait, only.pos=TRUE, min.pct=0.25, logfc.threshold=0.5) %>%
#   group_by(cluster) %>%
#   slice_max(n=20, order_by=avg_log2FC)
# markers.mait <- markers.mait %>%
#   select(avg_log2FC, p_val_adj, cluster, gene) %>%
#   left_join(seur.mait@meta.data %>%
#               select(cell_annot, RNA_snn_res.0.2) %>%
#               rename(cluster=RNA_snn_res.0.2) %>%
#               distinct(),
#             by="cluster") %>%
#   relocate(gene, cell_annot)
```

```{r preprocessing-mait-thymus2, fig.width=24, fig.height=8}
# Import object if necessary
seur.thymait <- readRDS("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/seurat_thymus-MAIT_2023-02-27.rds")

# Add thymic CD4 clusters to integrated object
table(rownames(seur@meta.data[seur@meta.data$group.ident=="MAIT_Thymus",]) == rownames(seur.thymait@meta.data)) # check rownames are in same order
seur@meta.data[seur@meta.data$group.ident=="MAIT_Thymus", "clusters_thyMAIT"] <- seur.thymait@meta.data$cell_annot
table(seur@meta.data[,c("group.ident", "clusters_thyMAIT")], useNA="ifany")


# Plot newly-assigned clusters & clusters from integrated object
# cols_mait <- c("#2171b5", "#6baed6", "#9ecae1", "#deebf7", "#c6dbef", "#f7fbff", "#4292c6")
# names(cols_mait) <- unique(seur.thymait$cell_annot)
cols_mait <- c("MAIT_c0" = "#d8443c",
               "MAIT_c1" = "#e09351",
               "MAIT_c2" = "gold",
               "MAIT_c3" = "#74c8c3",
               "MAIT_c4" = "#5a97c1",
               "MAIT_c5" = "#a40000",
               "MAIT_c6" = "#72bcd5")
SCpubr::do_DimPlot(seur.thymait,
                   group.by = "cell_annot",
                   label=T,
                   label.color="black",
                   legend.position = "none",
                   repel=T,
                   colors.use=cols_mait,
                   plot.title="MAIT thymocyte clusters",
                   font.size = 24) |
  SCpubr::do_DimPlot(seur.thymait, 
                   group.by = "new_clusters",
                   label=T,
                   label.color="black",
                   legend.position = "none",
                   repel=T,
                   colors.use=cols_integrated,
                   plot.title="Integrated object clusters",
                   font.size = 24) |
  SCpubr::do_DimPlot(seur, 
                     group.by = "clusters_thyMAIT",
                     na.value=adjustcolor("grey90", alpha.f = 0.5),
                     border.size=1,
                     label=T,
                     label.color="black",
                     legend.position = "none",
                     repel=T,
                     colors.use=cols_mait,
                   plot.title="MAIT clusters on integrated object",
                   font.size = 24)

# ggsave("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/mait_thy_overlap.jpeg", width=24, height=8)
```




### 2.5. NKT cells
```{r preprocessing-nkt}
seur.nkt <- preprocess(seurobj = subset(seur.filt, subset=group.ident=="NKT_Thymus"),  celltype = "NKTthy", ndim=10, res=0.3)

# Annotate
# Idents(seur.nkt) <- "cell_annot"
# markers <- FindAllMarkers(seur.nkt, only.pos=TRUE, min.pct=0.25, logfc.threshold=0.5) %>%
#   group_by(cluster) %>%
#   slice_max(n=5, order_by=avg_log2FC)

seur.nkt@meta.data$cell_annot <- case_when(
  seur.nkt@meta.data$seurat_clusters == 0 ~ "thyNKT_ccr7",
  seur.nkt@meta.data$seurat_clusters == 1 ~ "thyNKT_effFOSJUN",
  seur.nkt@meta.data$seurat_clusters == 2 ~ "thyNKT_ccr9",
  seur.nkt@meta.data$seurat_clusters == 3 ~ "thyNKT_cd8aa",
  seur.nkt@meta.data$seurat_clusters == 4 ~ "thyNKT_effector"
  # seur.nkt@meta.data$seurat_clusters == 5 ~ "thyNKT_IFNsig"
)
# saveRDS(seur.nkt, "~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/seurat_thymus-NKT_2023-02-27.rds")


ggpubr::ggarrange(DimPlot(seur.nkt, group.by="cell_annot", label=T, repel=T) +
                    theme(legend.position="none") + labs(title="Thymic NKT"),
                  DotPlot(seur.nkt, features=unique(c("CD4", "CD8A", "CD8B", "RAG1", markers$gene))) +
                    labs(x="", y="") + theme(axis.text.x=element_text(angle=90, hjust=1, vjust=0.5, size=7)),
                  ncol=2, widths = c(1.2,2))
# ggsave("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_CorrelationGEbtwTlineages/umap_thyNKT.jpeg", width=12, height=5)


# SCpubr
cols_nkt <- c("#9e9ac8", "#f2f0f7", "#cbc9e2", "#54278f", "#756bb1")
names(cols_nkt) <- unique(seur.nkt$cell_annot)
SCpubr::do_DimPlot(seur.nkt, 
                   group.by = "cell_annot",
                   label=T,
                   label.color="black",
                   legend.position = "none",
                   repel=T,
                   colors.use=cols_nkt,
                   font.size = 24)
# ggsave("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/scpubr_nkt.jpeg", width=6, height=6)


# # Markers NKT
# markers.nkt <- FindAllMarkers(seur.nkt, only.pos=TRUE, min.pct=0.25, logfc.threshold=0.5) %>%
#   group_by(cluster) %>%
#   slice_max(n=20, order_by=avg_log2FC)
# markers.nkt <- markers.nkt %>%
#   select(avg_log2FC, p_val_adj, cluster, gene) %>%
#   left_join(seur.nkt@meta.data %>%
#               select(cell_annot, RNA_snn_res.0.3) %>%
#               rename(cluster=RNA_snn_res.0.3) %>%
#               distinct(),
#             by="cluster") %>%
#   relocate(gene, cell_annot)
# 
# # Combine MAIT and NKT markers and export as .csv file
# markers.to.export <- rbind(markers.nkt, markers.mait) %>%
#   ungroup() %>%
#   select(-cluster)
# table(markers.to.export$cell_annot)
# write_csv(markers.to.export, "~/Desktop/top20markers_mait_nkt.csv")
```

```{r preprocessing-nkt-thymus2, fig.width=24, fig.height=8}
# Import object if necessary
seur.thynkt <- readRDS("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/thymus.nkt_02_28_23.RDS")

seur.thynkt@meta.data$cell_annot <- case_when(
  seur.thynkt@meta.data$new_clusters_NKT == 0 ~ "NKT_c0",
  seur.thynkt@meta.data$new_clusters_NKT == 1 ~ "NKT_c1",
  seur.thynkt@meta.data$new_clusters_NKT == 2 ~ "NKT_c2",
  seur.thynkt@meta.data$new_clusters_NKT == 3 ~ "NKT_c3",
  seur.thynkt@meta.data$new_clusters_NKT == 4 ~ "NKT_c4",
  seur.thynkt@meta.data$new_clusters_NKT == 5 ~ "NKT_c5",
  seur.thynkt@meta.data$new_clusters_NKT == 6 ~ "NKT_c6"
)
table(seur.thynkt@meta.data$cell_annot)

# Add thymic CD4 clusters to integrated object
table(rownames(seur@meta.data[seur@meta.data$group.ident=="NKT_Thymus",]) == rownames(seur.thynkt@meta.data)) # check rownames are in same order
seur@meta.data[seur@meta.data$group.ident=="NKT_Thymus", "clusters_thyNKT"] <- seur.thynkt@meta.data$cell_annot
table(seur@meta.data[,c("group.ident", "clusters_thyNKT")], useNA="ifany")


# Plot newly-assigned clusters & clusters from integrated object
# cols_nkt <- c("#9e9ac8", "#f2f0f7", "#cbc9e2", "#54278f", "#756bb1")
# names(cols_nkt) <- unique(seur.nkt$cell_annot)
cols_nkt <- c("NKT_c0" = "#d8443c",
               "NKT_c1" = "#e09351",
               "NKT_c2" = "gold",
               "NKT_c3" = "#74c8c3",
               "NKT_c4" = "#5a97c1",
               "NKT_c5" = "#a40000",
               "NKT_c6" = "#72bcd5")
SCpubr::do_DimPlot(seur.thynkt,
                   group.by = "cell_annot",
                   label=T,
                   label.color="black",
                   legend.position = "none",
                   repel=T,
                   colors.use=cols_nkt,
                   plot.title="NKT thymocyte clusters",
                   font.size = 24) |
  SCpubr::do_DimPlot(seur.thynkt, 
                   group.by = "new_clusters",
                   label=T,
                   label.color="black",
                   legend.position = "none",
                   repel=T,
                   colors.use=cols_integrated,
                   plot.title="Integrated object clusters",
                   font.size = 24) |
  SCpubr::do_DimPlot(seur, 
                     group.by = "clusters_thyNKT",
                     na.value=adjustcolor("grey90", alpha.f = 0.5),
                     border.size=1,
                     label=T,
                     label.color="black",
                     legend.position = "none",
                     repel=T,
                     colors.use=cols_nkt,
                   plot.title="NKT clusters on integrated object",
                   font.size = 24)

# ggsave("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/nkt_thy_overlap.jpeg", width=24, height=8)
```




### 2.6. GDT cells
```{r preprocessing-gdt}
seur.gd <- preprocess(seurobj = subset(seur.filt, subset=group.ident=="GD_Thymus"), celltype = "GDthy", ndim=10, res=0.2)

# Annotate
# Idents(seur.gd) <- "cell_annot"
# markers <- FindAllMarkers(seur.gd, only.pos=TRUE, min.pct=0.25, logfc.threshold=0.5) %>%
#   group_by(cluster) %>%
#   slice_max(n=10, order_by=avg_log2FC)

seur.gd@meta.data$cell_annot <- case_when(
  seur.gd@meta.data$seurat_clusters == 0 ~ "thyGDT_IFNsig",
  seur.gd@meta.data$seurat_clusters == 1 ~ "thyGDT_immat",
  seur.gd@meta.data$seurat_clusters == 2 ~ "thyGDT_ccr9",
  seur.gd@meta.data$seurat_clusters == 3 ~ "thyGDT_effector",
  seur.gd@meta.data$seurat_clusters == 4 ~ "thyGDT_immat_cycl",
  seur.gd@meta.data$seurat_clusters == 5 ~ "thyGDT_DP"
)
# saveRDS(seur.gd, "~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/seurat_thymus-GDT_2023-02-27.rds")

ggpubr::ggarrange(DimPlot(seur.gd, group.by="cell_annot", label=T, repel=T) +
                    theme(legend.position="none") + labs(title="Thymic GDT"),
                  DotPlot(seur.gd, features=unique(c("CD4", "CD8A", "CD8B", "RAG1", markers$gene))) +
                    labs(x="", y="") + theme(axis.text.x=element_text(angle=90, hjust=1, vjust=0.5, size=7)),
                  ncol=2, widths = c(1,2))
# ggsave("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_CorrelationGEbtwTlineages/umap_thyGDT.jpeg", width=15, height=5)



# SCpubr
cols_gdt <- c("#74a9cf", "#3690c0", "#045a8d", "#023858", "#0570b0", "#a6bddb")
names(cols_gdt) <- unique(seur.gd$cell_annot)
SCpubr::do_DimPlot(seur.gd, 
                   group.by = "cell_annot",
                   label=T,
                   label.color="white",
                   legend.position = "none",
                   repel=T,
                   colors.use=cols_gdt,
                   font.size = 24)
# ggsave("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/scpubr_gdt.jpeg", width=6, height=6)
```

```{r preprocessing-gdt-thymus2, fig.width=24, fig.height=8}
# Import object if necessary
seur.thygdt <- readRDS("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/seurat_thymus-GDT_2023-02-27.rds")

# Add thymic CD4 clusters to integrated object
table(rownames(seur@meta.data[seur@meta.data$group.ident=="GD_Thymus",]) == rownames(seur.thygdt@meta.data)) # check rownames are in same order
seur@meta.data[seur@meta.data$group.ident=="GD_Thymus", "clusters_thyGDT"] <- seur.thygdt@meta.data$cell_annot
table(seur@meta.data[,c("group.ident", "clusters_thyGDT")], useNA="ifany")


# Plot newly-assigned clusters & clusters from integrated object
cols_gdt <- c("#74a9cf", "#3690c0", "#045a8d", "#023858", "#0570b0", "#a6bddb")
names(cols_gdt) <- unique(seur.thygdt$cell_annot)
SCpubr::do_DimPlot(seur.thygdt, 
                   group.by = "cell_annot",
                   label=T,
                   label.color="black",
                   legend.position = "none",
                   repel=T,
                   colors.use=cols_gdt,
                   plot.title="CD8 thymocyte clusters",
                   font.size = 24) |
  SCpubr::do_DimPlot(seur.thygdt, 
                   group.by = "new_clusters",
                   label=T,
                   label.color="black",
                   legend.position = "none",
                   repel=T,
                   colors.use=cols_integrated,
                   plot.title="Integrated object clusters",
                   font.size = 24) |
  SCpubr::do_DimPlot(seur, 
                     group.by = "clusters_thyGDT",
                     na.value=adjustcolor("grey90", alpha.f = 0.5),
                     border.size=1,
                     label=T,
                     label.color="black",
                     legend.position = "none",
                     repel=T,
                     colors.use=cols_gdt,
                   plot.title="CD8 thymocyte clusters on integrated object",
                   font.size = 24)
# ggsave("~/Projects/HumanThymusProject/data/human-thymus/HumanData_12_AnalysisByLineage/gdt_thy_overlap.jpeg", width=24, height=8)
```


```{r merge-thymic-clusters}
seur@meta.data[seur@meta.data$group.ident=="CD4_Thymus", "clusters_thymus"] <- seur@meta.data[seur@meta.data$group.ident=="CD4_Thymus", "clusters_thyCD4"]
seur@meta.data[seur@meta.data$group.ident=="CD8_Thymus", "clusters_thymus"] <- seur@meta.data[seur@meta.data$group.ident=="CD8_Thymus", "clusters_thyCD8"]
seur@meta.data[seur@meta.data$group.ident=="MAIT_Thymus", "clusters_thymus"] <- seur@meta.data[seur@meta.data$group.ident=="MAIT_Thymus", "clusters_thyMAIT"]
seur@meta.data[seur@meta.data$group.ident=="NKT_Thymus", "clusters_thymus"] <- seur@meta.data[seur@meta.data$group.ident=="NKT_Thymus", "clusters_thyNKT"]
seur@meta.data[seur@meta.data$group.ident=="GD_Thymus", "clusters_thymus"] <- seur@meta.data[seur@meta.data$group.ident=="GD_Thymus", "clusters_thyGDT"]


SCpubr::do_DimPlot(seur, 
                   group.by = "clusters_thymus",
                   na.value=adjustcolor("grey90", alpha.f = 0.5),
                   border.size=1,
                   label=T,
                   label.color="black",
                   legend.position = "none",
                   repel=T,
                   # colors.use=cols_gdt,
                   # plot.title="CD8 thymocyte clusters on integrated object",
                   font.size = 24)


```



