---
title: "Human T cell data - Integrate with Park data"
output:
  html_document:
    df_print: paged
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```




## 1. IMPORT

### 1.1. Import librairies
```{r import-librairies, message=FALSE}
library(ggplot2)
library(gplots)
library(cowplot)
library(tidyverse)
library(dplyr)
library(Seurat)
library(SeuratData)
library(SeuratDisk)
library(RColorBrewer)
library(harmony)
# library(corrplot)
# library(pals)
library(VennDiagram)
library(ggVennDiagram)
library(MetaNeighbor)
library(SummarizedExperiment)
# library(ggalluvial)
# library(SingleCellExperiment)
```

```{R setup}
cols_integrated <- c("0" = "#f4c40f", "1" = "#b75347", "2" = "#d8443c",
                     "3" = "#e09351", "4" = "#2b9b81", "5" = "#421401",
                     "6" = "#92c051", "7" = "#9f5691", "8" = "#17154f",
                     "9" = "#74c8c3", "10" = "#5a97c1", "11" = "gold",
                     "12" = "#a40000", "13" = "#72bcd5", "14" = "grey50",
                     "15" = "orange", "16" = "blueviolet", "17" = "#0a2e57",
                     "18" = "#bdbdbd")

cols_park <- c("DN(early)" = "#78c679", "DN(P)" = "#41ab5d",
               "DN(Q)" = "#238443", "γδT" = "#92c051", "DP(P)" = "#b75347",
               "DP(Q)" = "#d8443c", "αβT(entry)" = "#e09351",
               "CD8+T"= "#5a97c1","CD8αα(I)" = "#421401",
               "CD8αα(II)" = "#0a2e57", "CD4+T"= "gold",
               "T(agonist)" = "#9f5691", "Treg(diff)" = "#9f5691",
               "Treg" = "blueviolet", "Th17" = "#a40000", "NKT" = "#72bcd5")
```

### 1.2. Import data - Gapin
```{r import-data, fig.height=8, fig.width=8}
# Import seurat object (generated by annotate-final-seurat.Rmd)
seur.gapin <- readRDS("data/human-thymus/HumanData_16_ParkIntegration/gapin_full_seu_gene_names_updated_anno.rds") 

# Sanity check
print(seur.gapin) # 78,607 cells
SCpubr::do_DimPlot(seur.gapin, 
                   group.by = "cell_clusters",
                   label=TRUE,
                   label.color="black",
                   legend.position = "none",
                   repel=TRUE,
                   #colors.use=cols_integrated,
                   font.size = 24)
# ggsave("data/human-thymus/HumanData_16_ParkIntegration/gapin_umap.jpeg",
# width=10, height=8)
```


### 1.3. Import data - Park
```{r import-park, fig.height=8, fig.width=8}
# generated y annotate-park-seurat.Rmd
seur.park <- readRDS('data/human-thymus/HumanData_16_ParkIntegration/park_full_seu_gene_names_updated_anno.rds')

# Sanity check
SCpubr::do_DimPlot(seur.park,
                   group.by = "cell_type",
                   label=TRUE,
                   label.color="black",
                   legend.position = "none",
                   repel=TRUE,
                   font.size = 24)
table(seur.park$cell_type, useNA="ifany")
```
## 2. INTEGRATE

#### 2.5.3. Merge data
```{r fullpark-gapin-integration2}
## KEEP ONLY COMMON GENES TO 2 DATASETS ####
# check out overlap gene names between Park data and our data
ggVennDiagram(
  x=list(rownames(seur.gapin), rownames(seur.park)),
  category.names = c("Gapin" , "Park"),
  label_alpha=0,
  label="count"
) +
  ggplot2::scale_fill_gradient(low="white",high = "blue")

# keep only genes common to the 2 datasets
common_genes <- intersect(rownames(seur.gapin), rownames(seur.park))
length(common_genes) # 13,988 genes
seur.gapin <- seur.gapin[common_genes,]
seur.park <- seur.park[common_genes,]

seur.combined <- merge(seur.gapin, seur.park)

# Sanity checks
sum(ncol(seur.gapin), ncol(seur.park)) # sanity check number of cells
seur.gapin@assays[["RNA"]]@data[5:10,1:5]
seur.combined@assays[["RNA"]]@data[5:10,1:5]
seur.park@assays[["RNA"]]@data[5:10,1:5]
seur.combined@assays[["RNA"]]@data[5:10,78608:78613] # same data counts

table(seur.combined@meta.data$tissue, useNA="ifany")
table(seur.combined@meta.data$study, useNA="ifany")
table(seur.combined@meta.data$cell_clusters, useNA="ifany")
table(seur.combined@meta.data$Batch, useNA="ifany")
table(seur.combined@meta.data$Anno_level_1, useNA="ifany")
table(seur.combined@meta.data$Anno_level_2, useNA="ifany")
table(seur.combined@meta.data$Anno_level_3, useNA="ifany")
table(seur.combined@meta.data$Anno_level_4, useNA="ifany")
table(seur.combined@meta.data$Anno_level_5, useNA="ifany")

# Save seurat object
saveRDS(seur.combined, "data/human-thymus/HumanData_16_ParkIntegration/seurat_integrated_fullpark_fullgapin_23-05-02.rds")
```


#### 2.5.4. Get markers
First at high level:
- DP
- cTEC
- mTEC
- iNKT
- MAIT

```{r marker functions}
extract_markers <- function(celltype, seur, min.pct=0.1, logfc.thr=0.25,
                            only.pos=TRUE, verbose=TRUE) {
  if (verbose) cat(celltype)
  markers <- FindMarkers(seur, ident.1=celltype, min.pct=min.pct,
                         logfc.threshold = logfc.thr, only.pos=only.pos)
  markers <- markers %>%
    arrange(-avg_log2FC) %>%
    rownames_to_column("gene") %>%
    mutate(celltype=celltype,
           min.pct=min.pct,
           logfc.thr=logfc.thr) %>%
    as_tibble
  return(markers)
}

format_markers <- function(markerlist, nr_marker=50) {
  tmp <- markerlist %>% 
    head(nr_marker) %>% 
    pull(genes)
  if (length(tmp) < nr_marker) {
    tmp <- c(tmp, rep(NA, nr_marker-length(tmp)))
  }
  return(tmp)
}
```

- PARK MARKERS
```{r fullpark-gapin-integration4, fig.height=10, fig.width=10}

# Markers bigger categories

seur.park.stromal <- subset(seur.park,
                      subset=Anno_level_0=="stromal")
seur.park.lymphoid <- subset(seur.park,
                      subset=Anno_level_0=="lymphoid")

Idents(seur.park) <- "Anno_level_3"
park_markers_level_3 <- lapply(c("DP", "cTEC", "mTEC"),
                       extract_markers, seur.park, min.pct=0.1,
                       logfc.thr=0.25) %>%
  bind_rows
  
Idents(seur.park.stromal) <- "Anno_level_3"
park.stromal_markers_level_3 <- lapply(c("cTEC", "mTEC"),
                       extract_markers, seur.park.stromal, min.pct=0.1,
                       logfc.thr=0.25) %>%
  bind_rows

Idents(seur.park.lymphoid) <- "Anno_level_3"
park.lymphoid_markers_level_3 <- extract_markers("DP", seur.park.lymphoid,
                                                 min.pct=0.1, logfc.thr=0.25)

```

- GAPIN MARKERS
```{r fullpark-gapin-integration5, fig.height=10, fig.width=10}
seur.gapin.thymus <-subset(seur.gapin,
                      subset=tissue=="Thymus")

Idents(seur.gapin.thymus) <- "Anno_level_4"
gapin_markers_level_4 <- lapply(c("thymus_NKT", "thymus_MAIT"),
                       extract_markers, seur.gapin.thymus, min.pct=0.1,
                       logfc.thr=0.25) %>%
  bind_rows


Idents(seur.gapin.thymus) <- "Anno_level_5"
gapin_markers_level_5 <- lapply(c("iNKT_naive", "iNKT_effector_Tcm",
                                  "iNKT_effector_Tem", "MAIT_naive",
                                  "MAIT_effector_Tem"),
                       extract_markers, seur.gapin.thymus, min.pct=0.1,
                       logfc.thr=0.25) %>%
  bind_rows


DimPlot(seur.gapin.thymus, reduction="UMAP_50", group.by = "Anno_level_3", label=T)

# write.csv2(final_markers, "~/Projects/HumanThymusProject/data/human-thymus/HumanData_16_ParkIntegration/cellphonedb_markers.csv")
# 
```

```{r}

metadata <- seur.combined@meta.data %>% 
  rownames_to_column("barcode_sample") %>%
  as_tibble %>%
  select(barcode_sample, Anno_level_3, Anno_level_4, study) %>%
  mutate(cell_type=case_when(study == "gapin_data" ~ Anno_level_4,
                             TRUE ~ Anno_level_3)) %>%
  select(barcode_sample, cell_type)

write_delim(metadata, "data/human-thymus/HumanData_16_ParkIntegration/metadata.tsv",
            delim="\t")

markers_TT <- rbind(park.lymphoid_markers_level_3, gapin_markers_level_4) %>%
  select(celltype, gene)
  
 
markers_Tstromal <- rbind(park.stromal_markers_level_3, gapin_markers_level_4) %>%
  select(celltype, gene) 
  
markers_all <- rbind(park.stromal_markers_level_3, park.lymphoid_markers_level_3, gapin_markers_level_4) %>%
  select(celltype, gene)

write_delim(markers_TT, "data/human-thymus/HumanData_16_ParkIntegration/markers_TT.tsv",
            delim="\t")
write_delim(markers_Tstromal, "data/human-thymus/HumanData_16_ParkIntegration/markers_Tstromal.tsv",
            delim="\t")
write_delim(markers_all, "data/human-thymus/HumanData_16_ParkIntegration/markers.tsv",
            delim="\t")

write_delim(park.stromal_markers_level_3, "data/human-thymus/HumanData_16_ParkIntegration/markers_cTEC_mTEC.tsv",
            delim="\t")
```

```{r covert to h5ad objects}
SaveH5Seurat(seur.combined,
             filename = "data/human-thymus/HumanData_16_ParkIntegration/park_garpin_full_seu_gene_names_updated_anno.h5Seurat")
Convert("data/human-thymus/HumanData_16_ParkIntegration/park_garpin_full_seu_gene_names_updated_anno.h5Seurat", dest = "h5ad")
```