---
title: "Prepare data to run pyMetaNeighbor with the Human Thymus Atlas (Park et al.)"
author: "Salomé Carcy"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  fig.width = 5,
  fig.height = 5,
  warning = FALSE,
  message = FALSE,
  attr.output='style="max-height: 300px;"',
  root.dir = "~/Projects/HumanThymusProject/"
)
```




# IMPORT

## Import librairies
```{r import-librairies}
library(ggplot2)
library(tidyverse)
library(dplyr)
library(Seurat)
library(SCpubr)

setwd("~/Projects/HumanThymusProject/")
source("~/Projects/HumanThymusProject/scripts/colors_universal.R")
```


## Import data
```{r import-data, fig.width=7}
# our integrated dataset
seur_integrated <- readRDS("./data_geo/seurat_objects/seurat_human_integrated_object_23_12_01.rds")
seur_thymus <- subset(seur_integrated, subset=tissue=="Thymus") # keep only thymocytes
do_DimPlot(
  seur_thymus,
  group.by = "clusters_integrated_data",
  reduction = "umap_integrated",
  colors.use = cols_integrated,
  legend.position="right"
)

# Park et al. thymocyte data (corresponding to Fig 2C)
seur_park <- readRDS("./data_github/park_dataset/park_seurat_human_thymocytes.rds")
do_DimPlot(
  seur_park,
  group.by="cell_types",
  legend.position="right",
  colors.use = cols_park,
  label=T
)
```




# PREPARE DATA FOR METANEIGHBOR

## Prepare HVGs
```{r prep-hvg}
# subset to common genes
common_genes <- intersect(rownames(seur_thymus), rownames(seur_park))
seur_thymus <- seur_thymus[common_genes,]
seur_park <- seur_park[common_genes,]

# get HVGs
seur_thymus <- FindVariableFeatures(seur_thymus, nfeatures = 2000)
seur_park <- FindVariableFeatures(seur_park, nfeatures = 2000)

ggVennDiagram::ggVennDiagram(
  x=list(VariableFeatures(seur_thymus), VariableFeatures(seur_park)),
  category.names = c("Current study HVGs" , "Park HVGs"),
  label_alpha=0,
  label="count"
)+
  ggplot2::scale_fill_gradient(low="white",high = "blue") # 896 common HVGs

hvg.total <- unique(c(VariableFeatures(seur_thymus), VariableFeatures(seur_park)))
length(hvg.total) # 3,104 genes


# XXXXXX
# obtain HVGs from Park et al. dataset
seur_park <- FindVariableFeatures(seur_park, nfeatures = 2000)

ggVennDiagram::ggVennDiagram(
  x=list(VariableFeatures(seur_thymus), VariableFeatures(seur_park)),
  category.names = c("Current study HVGs" , "Park HVGs"),
  label_alpha=0,
  label="count"
)+
  ggplot2::scale_fill_gradient(low="white",high = "blue") # 549 common HVGs

hvg.total <- unique(c(VariableFeatures(seur_thymus), VariableFeatures(seur_park)))
length(hvg.total) # 3,451 genes
# XXXXXXX
```


## Prepare metadata
```{r prep-metadata}
# our data: keep only columns of interest
seur_thymus@meta.data <- seur_thymus@meta.data[,c(
  "nCount_RNA",
  "nFeature_RNA",
  "clusters_integrated_data"
)]
colnames(seur_thymus@meta.data) <- c("nCount", "nFeature", "clusters_to_compare")
seur_thymus@meta.data$clusters_to_compare <- as.character(seur_thymus@meta.data$clusters_to_compare)
seur_thymus@meta.data$clusters_to_compare <- paste0("c", seur_thymus@meta.data$clusters_to_compare)
seur_thymus@meta.data$study <- "gapin_data"
head(seur_thymus@meta.data)

# park data: keep only columns of interest
seur_park@meta.data <- seur_park@meta.data[,c(
  "nCount_originalexp",
  "nFeature_originalexp",
  "cell_types"
)]
colnames(seur_park@meta.data) <- c("nCount", "nFeature", "clusters_to_compare")
seur_park@meta.data$clusters_to_compare <- as.character(seur_park@meta.data$clusters_to_compare)
seur_park@meta.data$study <- "park_data"
head(seur_park@meta.data)

# merge metadata
# table(colnames(seur_park) %in% colnames(seur_thymus), useNA="ifany") # it's all FALSE: different cell IDs
metadata_merged <- rbind(seur_thymus@meta.data, seur_park@meta.data)
table(metadata_merged$study)
# nrow(metadata_merged)==ncol(seur_thymus)+ncol(seur_park)
```


XXXXXXXXX
## Merge Seurat objects (to delete?)
Now, merge the seurat objects.
```{r merge-seurat-to-delete}
# Merge seurat objects
seur_merged <- merge(seur_thymus, y=seur_park)

# sanity checks
ncol(seur_merged) == ncol(seur_thymus) + ncol(seur_park) # total nb of samples
length(union(rownames(seur_thymus), rownames(seur_park))) # total nb of genes
print(seur_merged)
3316+13888+13191+13888
```
XXXXXXXXX


## Prepare count matrices
Subset the counts to common genes.
```{r prep-counts}
# get counts matrices 
thym.counts <- seur_thymus[["RNA"]]@counts
park.counts <- seur_park[["originalexp"]]@counts

# make sure they are counts and not log normalized data
thym.counts[5:10,1:5]
park.counts[1:5,1:5]

# check out how many common genes
ggVennDiagram::ggVennDiagram(
  x=list(rownames(thym.counts), rownames(park.counts)),
  category.names = c("Current study genes" , "Park genes"),
  label_alpha=0,
  label="count"
)+
  ggplot2::scale_fill_gradient(low="white",high = "blue") # 13,888 common genes

# subset to common genes
# common_genes <- intersect(rownames(thym.counts), rownames(park.counts))
# thym.counts <- thym.counts[common_genes,]
# park.counts <- park.counts[common_genes,]

dim(thym.counts)
dim(park.counts)

# merge
counts_merged <- cbind(thym.counts, park.counts)
ncol(counts_merged)==ncol(thym.counts)+ncol(park.counts)
dim(counts_merged)
```




# EXPORT FOR METANEIGHBOR

## Merge everything into a seurat object
```{r prep-seurat-combined}
# sanity checks
# table(rownames(metadata_merged)==colnames(counts_merged), useNA="ifany") # all TRUE

seur.total <- CreateSeuratObject(counts=counts_merged, meta.data=metadata_merged)
print(seur.total)
```


## Convert to h5ad file
```{r convert-h5ad, echo=T, eval=F}
# convert to .h5ad
SeuratDisk::SaveH5Seurat(
  seur.total,
  filename = "./data_github/park_dataset/pymtn/human_thym_merged_with_park_240902.h5Seurat"
  )
SeuratDisk::Convert(
  "./data_github/park_dataset/pymtn/human_thym_merged_with_park_240902.h5Seurat",
  dest = "h5ad"
  )
```


## Export HVGs
```{r export-hvg, echo=T, eval=F}
# export HVG list into .csv file
hvg.df <- data.frame(
  "features"=rownames(seur.total),
  "highly_variable"=ifelse(rownames(seur.total)%in%hvg.total2, T, F)
)
table(hvg.df$highly_variable, useNA="ifany")
table(hvg.df[hvg.df$highly_variable==T, "features"]%in%hvg.total2, useNA="ifany") # sanity check
write.csv(hvg.df, "./data_github/park_dataset/pymtn/human_thym_merged_with_park_list_hvg_240902.csv")
```




# SESSION INFO
```{r}
sessionInfo()
```


