---
title: "CX3CR1 gradient"
output: html_notebook
---

# 1.IMPORT

## 1.1.librairies
```{r import-library}
library(Seurat)
library(ggplot2)
library(cowplot)
library(pheatmap)
library(tidyverse)
setwd("~/Projects/HumanThymusProject/")

source("./scripts-final/colors_universal.R")
```

## 1.2. data
```{r import-data}
# seurat object
seur.human <- readRDS("~/Projects/HumanThymusProject/data/raw_data/human_data/seurat_filtered_harmony_08_28_23.RDS")
DimPlot(seur.human, reduction="UMAP_50", group.by="new_clusters")+
  scale_color_manual(values=cols_integrated)

# GEP usage
gep_usage <- read.table("~/Projects/HumanThymusProject/data/human-PBMC/HumanData_20_RibbonPlotCellStateToID/cNMF_output/non_imputed_cNMF_allcells.usages.k_12.dt_0_02.consensus.txt", header=T)
colnames(gep_usage) <- paste0("gep", c(2,5,3,1,4,12,6,7,8,10,9,11), "_usage")
gep_usage$gep12_usage <- NULL
```




# 2.CX3CR1 GRADIENT

## 2.1. format data
```{r}
# extract CX3CR1 expression level
normcounts <- data.frame("cx3cr1"=seur.human@assays$RNA@data["CX3CR1",])
head(normcounts)

# extract metadata of interest
table(rownames(normcounts)==rownames(seur.human@meta.data))
df <- cbind(normcounts,
            seur.human@meta.data[,c("Tissue", "cell.ident", "new_clusters")]) %>%
  mutate(new_clusters=factor(new_clusters, levels=0:17))
head(df)

# add GEP usage?
# gep_usage$score_max <- apply(gep_usage, 1, max)
gep_usage$gep_assign <- gsub("_.*", "", colnames(gep_usage)[apply(gep_usage, 1, which.max)])
head(gep_usage)
table(gep_usage$gep_assign, useNA="ifany")
table(rownames(gep_usage)==rownames(df), useNA="ifany")

df <- df %>%
  mutate(gep_assign=factor(gep_usage$gep_assign, levels=paste0("gep", c(1:11)))) #%>%
  # filter(Tissue=="PBMC") %>%
  # select(-Tissue) # %>%
  # arrange by cluster, and then cx3cr1
  # arrange(new_clusters, cell.ident, cx3cr1)
dim(df) # 40986 cells with MAITs removed (PBMC only)
table(df$gep_assign)

# df <- df %>%
  # filter(!gep_assign %in% c("gep2", "gep7", "gep11"))
```


## 2.2. plot heatmap
forget it, it doesn't look great
```{r, fig.height=8, fig.width=5}
# pheatmap(df %>% filter(cell.ident=="GD") %>% select(cx3cr1),
#          show_rownames=F,
#          show_colnames=F,
#          cluster_cols=F,
#          cluster_rows=F,
#          annotation_row= df %>% filter(cell.ident=="GD") %>% select(-cx3cr1),
#          annotation_colors=list(
#            new_clusters=cols_integrated,
#            cell.ident=cols_lineages
#            )
#          )
# 
# df %>% filter(cell.ident=="CD4") %>% select(-cx3cr1) %>% count(new_clusters)
```


## 2.3. plot violin plots
```{r, fig.height=10, fig.width=5}
ggplot(df, aes(x=gep_assign, y=cx3cr1))+
  # geom_boxplot(outlier.shape=NA)+
  geom_jitter(aes(color=Tissue), width=0.5, size=0.1)+
  geom_violin()+
  facet_wrap(~cell.ident, ncol=1)+
  scale_color_manual(values=c("#cb181d", "#9ecae1"))+
  labs(x="", y="Cx3cr1 normalized expression level")+
  theme_cowplot()+
  theme(axis.text.x = element_text(angle=45, hjust=1))+
  guides(colour = guide_legend(override.aes = list(size=3)))
# ggsave("./plots/cx3cr1_gradient.jpeg", width=4, height=10)
```



# 3. GZM EXPRESSION

## 3.1. format data
```{r}
# extract GZMB and GZMK expression level
normcounts2 <- data.frame("gzmh"=seur.human@assays$RNA@data["GZMH",],
                          "gzmb"=seur.human@assays$RNA@data["GZMB",],
                          "gzmk"=seur.human@assays$RNA@data["GZMK",],
                          "gzma"=seur.human@assays$RNA@data["GZMA",])
head(normcounts2)

# extract metadata of interest
table(rownames(normcounts2)==rownames(seur.human@meta.data))
df_gzm <- cbind(normcounts2,
                seur.human@meta.data[,c("Tissue", "cell.ident", "new_clusters", "TCR_Alpha_Gamma_V_gene_Dominant", "TCR_Beta_Delta_V_gene_Dominant")]) %>%
  mutate(new_clusters=factor(new_clusters, levels=0:17)) %>%
  # simplify VG and VD
  mutate(tcr_gamma=case_when(
    TCR_Alpha_Gamma_V_gene_Dominant %in% grep("TRAV", TCR_Alpha_Gamma_V_gene_Dominant, value=T) ~ "Valpha",
    TCR_Alpha_Gamma_V_gene_Dominant %in% grep("TRGV9", TCR_Alpha_Gamma_V_gene_Dominant, value=T) ~ "VG9",
    TCR_Alpha_Gamma_V_gene_Dominant %in% grep("TRGV", TCR_Alpha_Gamma_V_gene_Dominant, value=T) ~ "VGother",
    .default = "unknown"
    ),
    tcr_delta=case_when(
    TCR_Beta_Delta_V_gene_Dominant %in% grep("TRBV", TCR_Beta_Delta_V_gene_Dominant, value=T) ~ "Vbeta",
    TCR_Beta_Delta_V_gene_Dominant %in% grep("TRDV1", TCR_Beta_Delta_V_gene_Dominant, value=T) ~ "VD1",
    TCR_Beta_Delta_V_gene_Dominant %in% grep("TRDV2", TCR_Beta_Delta_V_gene_Dominant, value=T) ~ "VD2",
    TCR_Beta_Delta_V_gene_Dominant %in% grep("TRDV3", TCR_Beta_Delta_V_gene_Dominant, value=T) ~ "VD3",
    .default = "unknown"
    ),
  ) %>%
  mutate(tcr_vd2vg9=case_when(
    cell.ident=="GD" & tcr_delta=="VD2" & tcr_gamma=="VG9" ~ "GD(TRDV2_TRGV9)",
    cell.ident=="GD" & tcr_delta %in% c("VD1", "VD3")      ~ "GD(TRDV2neg)",
    .default = "other"
    ))
head(df_gzm)

# sanity checks
# table(df_gzm[,c("TCR_Alpha_Gamma_V_gene_Dominant", "tcr_gamma")], useNA="ifany")
# table(df_gzm[,c("cell.ident", "tcr_gamma")], useNA="ifany") # PROBLEM: some GD with Valpha segment....?.?...
# table(df_gzm[,c("TCR_Beta_Delta_V_gene_Dominant", "tcr_delta")], useNA="ifany")
# table(df_gzm[,c("cell.ident", "tcr_delta")], useNA="ifany") # PROBLEM: some GD with Vbeta segment....?.?...
# table(df_gzm[,c("tcr_gamma", "tcr_vd2vg9")], useNA="ifany")
# table(df_gzm[,c("tcr_delta", "tcr_vd2vg9")], useNA="ifany")


# add GEP usage
table(rownames(gep_usage)==rownames(df_gzm), useNA="ifany")
df_gzm <- df_gzm %>%
  select(-c(TCR_Alpha_Gamma_V_gene_Dominant, TCR_Beta_Delta_V_gene_Dominant)) %>%
  mutate(gep_assign=factor(gep_usage$gep_assign, levels=paste0("gep", c(1:11)))) %>%
  pivot_longer(cols=c(gzmh, gzmb, gzmk, gzma), names_to="gene", values_to="normcount")
#%>%
  # filter(Tissue=="PBMC") %>%
  # select(-Tissue) # %>%
  # arrange by cluster, and then cx3cr1
  # arrange(new_clusters, cell.ident, cx3cr1)
dim(df_gzm) # 40986 cells with MAITs removed (PBMC only)
table(df_gzm$gep_assign)
```

## 3.2. plot violin plots
```{r, fig.height=10, fig.width=10}
ggplot(df_gzm, aes(x=factor(gene, levels=c("gzmk", "gzma", "gzmb", "gzmh")), y=normcount))+
  geom_jitter(aes(color=Tissue), width=0.4, size=0.01)+
  geom_violin()+
  facet_grid(cell.ident~gep_assign)+
  scale_color_manual(values=c("#cb181d", "#9ecae1"))+
  labs(x="", y="Normalized expression level")+
  theme_cowplot()+
  theme(axis.text.x = element_text(angle=45, hjust=1))+
  guides(colour = guide_legend(override.aes = list(size=3)))
ggsave("./plots/gzm_per_gep_lineage.jpeg", width=10, height=8)


# Separate by GD type
df_gzm %>%
  mutate(cell.ident=case_when(
    cell.ident=="GD" & tcr_vd2vg9=="GD(TRDV2_TRGV9)" ~ "GD (TRDV2_GV9)",
    cell.ident=="GD" & tcr_vd2vg9=="GD(TRDV2neg)"    ~ "GD (TRDV2neg)",
    cell.ident=="GD" & tcr_vd2vg9=="other"           ~ "GD (other)",
    .default=cell.ident
  )) %>%
  filter(cell.ident != "GD (other)") %>%
  # plot
  ggplot(aes(x=factor(gene, levels=c("gzmk", "gzma", "gzmb", "gzmh")), y=normcount))+
  geom_jitter(aes(color=Tissue), width=0.4, size=0.01)+
  geom_violin()+
  facet_grid(cell.ident~gep_assign)+
  scale_color_manual(values=c("#cb181d", "#9ecae1"))+
  labs(x="", y="Normalized expression level")+
  theme_cowplot()+
  theme(axis.text.x = element_text(angle=45, hjust=1))+
  guides(colour = guide_legend(override.aes = list(size=3)))
ggsave("./plots/gzm_per_gep_lineage_GDsplit.jpeg", width=10, height=10)
# table(df_gzm[,c("cell.ident", "tcr_vd2vg9")], useNA="ifany")
# table(test[,c("cell.ident", "tcr_vd2vg9")], useNA="ifany")
```


## 3.3. scatter plot gep6/gep5 usage

```{r}
cbind(normcounts2,
              seur.human@meta.data[,c("Tissue", "cell.ident", "new_clusters", "TCR_Alpha_Gamma_V_gene_Dominant", "TCR_Beta_Delta_V_gene_Dominant")]) %>%
  mutate(new_clusters=factor(new_clusters, levels=0:17)) %>%
  # add gep_usage
  mutate(gep5_usage=gep_usage$gep5_usage,
         gep6_usage=gep_usage$gep6_usage) %>%
  # keep only PBMC
  filter(Tissue=="PBMC") %>%
  # keep only cells that have non-0 gzmb and gzmk
  # filter(gep5_usage>0 & gep6_usage>0) %>%
  # mutate(gzmb=case_when(gzmb==0 ~ 0.1, .default=gzmb),
  #        gzmk=case_when(gzmk==0 ~ 0.1, .default=gzmk)) %>%
         # gep5_usage=case_when(gep5_usage==0 ~ 1e-10, .default=gep5_usage),
         # gep6_usage=case_when(gep6_usage==0 ~ 1e-10, .default=gep6_usage)) %>%
  # get ratio gzmb/gzmk
  mutate(ratio_gzmb_gzmk=gzmb/gzmk,
         ratio_gep6_gep5=gep6_usage/gep5_usage) %>%
  # PLOT
  # ggplot(aes(x=log(ratio_gep6_gep5), y=log(ratio_gzmb_gzmk)))+
  ggplot(aes(x=gep6_usage, y=gzmk, color=new_clusters))+
  geom_point()+
  scale_color_manual(values=cols_integrated)
```




# 4. FIGURE 5 GENES PER LINEAGE

## 4.1. format data

```{r, fig.width=15, fig.height=4}
# extract GZMB and GZMK expression level
genes_of_interest <- c("GPR183", "S1PR4", "CXCR3", "CCR1", "CCR2", "CCR5", "CCR6", "CXCR6", "CXCR2",
                       "IL2RA", "IL6R", "IL4R", "IL18R1", "IL18RAP", "IL23R", "IL12RB2", "IFNGR1", "IL17RE", "IL17RC",
                       "LTB", "IFNG", "IL7", "IL17C", "XCL2", "CCL3", "CCL4", "CCL5", "CCL27", "CCL4L2",
                       "GZMK", "GZMA", "GZMB", "GZMH", "GNLY",
                       "KLRG1", "NCR3", "KLRB1", "NCR1", "KLRC2", "KLRC3","KIR3DL2", "KIR2DL3", "KLRD1", "KLRC4", "KLRF1", "KLRK1", "LILRB1",
                       "ITGB1", "ITGAX", "ITGAM", "ITGAL", "ITGB2", "ITGAV")
genes_of_interest.df <- data.frame("gene"=genes_of_interest,
                                   "geneclass"=c(rep("Migration", 9),
                                                 rep("Cytokine receptors", 10),
                                                 rep("Cytokines and Chemokines", 10),
                                                 rep("Cytotoxicity", 5),
                                                 rep("NK receptors", 13),
                                                 rep("Integrins", 6))) %>%
  mutate(geneclass=factor(geneclass, levels=c("Migration", "Cytokine receptors", "Cytokines and Chemokines", "Cytotoxicity", "NK receptors", "Integrins")))

normcounts3 <- t(data.frame(seur.human@assays$RNA@data[genes_of_interest,]))
head(normcounts3)

# reformat
table(rownames(normcounts3)==rownames(seur.human@meta.data))
table(rownames(normcounts3)==rownames(gep_usage))

# sanity check can reproduce fig5
cbind(normcounts3,
      seur.human@meta.data[,c("Tissue", "cell.ident", "new_clusters")],
      "gep_assign"=gep_usage$gep_assign) %>%
  mutate(new_clusters=factor(new_clusters, levels=0:17)) %>%
  # keep only PBMCs and GEP4-6
  filter(Tissue=="PBMC" & gep_assign %in% c("gep4", "gep5", "gep6")) %>%
  select(-Tissue) %>%
  # get percent_express
  pivot_longer(cols=all_of(genes_of_interest), names_to="gene", values_to="normcount") %>%
  # get average expression
  group_by(gep_assign, gene) %>%
  mutate(percent_expressed=sum(normcount>0)*100/n()) %>%
  summarise(average_normcount=mean(normcount),
            percent_expressed=unique(percent_expressed)) %>%
  ungroup() %>%
  # z-score
  group_by(gene) %>%
  mutate(zscore=(average_normcount-mean(average_normcount))/sd(average_normcount)) %>%
  ungroup() %>%
  # add gene class
  left_join(genes_of_interest.df, by="gene") %>%
  # PLOT
  ggplot(aes(x=factor(gene, levels=genes_of_interest), y=gep_assign))+
  geom_point(aes(size = percent_expressed, fill=zscore), color="black", pch=21)+
  facet_wrap(~geneclass, nrow=1, scales="free_x")+
  scale_fill_gradient(low="#fcfbfd", high="#3f007d")+
  labs(x="", y="")+
  theme_cowplot()+
  theme(axis.text.x=element_text(angle=45, hjust=1))
  
```

## 4.2. bubble plot by lineage

```{r, fig.width=15, fig.height=10}
# sanity check can reproduce fig5
df.manygenes <- cbind(normcounts3,
      seur.human@meta.data[,c("Tissue", "cell.ident", "new_clusters")],
      "gep_assign"=gep_usage$gep_assign) %>%
  mutate(new_clusters=factor(new_clusters, levels=0:17)) %>%
  # keep only PBMCs and GEP4-6
  filter(Tissue=="PBMC" & gep_assign %in% c("gep4", "gep5", "gep6")) %>%
  select(-Tissue) %>%
  # sanity check number of cells per group
  # group_by(gep_assign, cell.ident) %>%
  # summarise(nbcells=n()) # lowest is 44 NKT in GEP6
  # get percent_express
  pivot_longer(cols=all_of(genes_of_interest), names_to="gene", values_to="normcount") %>%
  # get average expression
  group_by(gep_assign, gene, cell.ident) %>%
  mutate(percent_expressed=sum(normcount>0)*100/n()) %>%
  summarise(average_normcount=mean(normcount),
            percent_expressed=unique(percent_expressed)) %>%
  ungroup() %>%
  # z-score
  group_by(gene) %>%
  mutate(zscore=(average_normcount-mean(average_normcount))/sd(average_normcount)) %>%
  ungroup() %>%
  # add gene class
  left_join(genes_of_interest.df, by="gene")

df.manygenes %>%
  # PLOT
  ggplot(aes(x=factor(gene, levels=genes_of_interest), y=gep_assign))+
  geom_point(aes(size = percent_expressed, fill=zscore), color="black", pch=21)+
  facet_grid(cell.ident~geneclass,scales="free_x")+
  scale_fill_gradient(low="#fcfbfd", high="#3f007d")+
  labs(x="", y="")+
  theme_cowplot()+
  theme(axis.text.x=element_text(angle=45, hjust=1))
```


## 4.3. violin plot by lineage
```{r, fig.width=15, fig.height=10}
cbind(normcounts3,
      seur.human@meta.data[,c("Tissue", "cell.ident", "new_clusters")],
      "gep_assign"=gep_usage$gep_assign) %>%
  mutate(new_clusters=factor(new_clusters, levels=0:17)) %>%
  # keep only PBMCs and GEP4-6
  filter(Tissue=="PBMC" & gep_assign %in% c("gep4", "gep5", "gep6")) %>%
  select(-Tissue) %>%
  # get percent_express
  pivot_longer(cols=all_of(genes_of_interest), names_to="gene", values_to="normcount") %>%
  # add gene class
  left_join(genes_of_interest.df, by="gene") %>%
  # PLOT ----
  ggplot(aes(x=gep_assign, y=normcount))+
  geom_jitter(aes(color=geneclass), width=0.4, size=0.01)+
  geom_violin()+
  facet_grid(cell.ident~factor(gene, levels=genes_of_interest))+
  scale_color_manual(values=c("Migration"="#08306b",
                              "Cytokine receptors"="#74c476",
                              "Cytokines and Chemokines"="#993404",
                              "Cytotoxicity"="#fec44f",
                              "NK receptors"="#fa9fb5",
                              "Integrins"="#807dba"))+
  labs(x="", y="Normalized expression level")+
  theme_cowplot()+
  theme(axis.text.x = element_text(angle=45, hjust=1))+
  guides(colour = guide_legend(override.aes = list(size=3)))
# ggsave("./plots/allgenes_by_gep_lineage2.jpeg", width=40, height=10)
```

