---
title: "Human data - Comparison of preprocessing methods"
output: html_notebook
---


## 1. Import

```{r import-librairies}
# Libraries
library(ggplot2)
library(cowplot)
library(Seurat)
library(SeuratWrappers)
library(harmony)
library(Matrix)
library(tidyverse)
```


```{r import-data}
# Data (sorted human iNKT cells from 3 subjects)
path.plots <- "~/Projects/20220809_Thymic-iNKT-CrossSpecies/data/00_Reproduce_UMAPs"
path.data <- "~/Projects/20220809_Thymic-iNKT-CrossSpecies/data/raw_data/human_data"
human5 <- read.csv(file.path(path.data, "CUThy13_220225_SampleTag05_hs_NKT_RSEC_MolsPerCell.csv"), sep=",", header=T, skip=7) # 404 cells
human8 <- read.csv(file.path(path.data, "CUTHY11BDRscRNA_seq_091621_SampleTag08_hs_NKT_RSEC_MolsPerCell.csv"), sep=",", header=T, skip=8) # 1913 cells
human12 <- read.csv(file.path(path.data, "CUTHY12BDRscRNA_seq_211101_SampleTag12_hs_NKT_RSEC_MolsPerCell.csv"), sep=",", header=T, skip=8) # 344 cells

# Current df format:
# Rownames || Cell_Index | Gene1 | Gene2 | ...
#   -      ||   421953   |   0   |   0   | ...
#   -      ||   459121   |   0   |   3   | ...

# Invert the dataframes (cells as columns and genes as rows) and transform to dgCMatrix
convert_to_matrix <- function(df){
  rownames(df) <- df$Cell_Index
  df$Cell_Index <- NULL
  df <- t(df)
  df <- Matrix(df, sparse=T)
  return(df)
}

mat.hu5  <- convert_to_matrix(human5) # 404 cells
mat.hu8  <- convert_to_matrix(human8) # 1913 cells
mat.hu12 <- convert_to_matrix(human12) # 344 cells
```




## 2. Preprocessing

```{r create-seurat}
# Create Seurat Object, keep only features expressed in at least 1 cell
seur.h5  <- CreateSeuratObject(mat.hu5, project="Hu_Thymus_NKT_5", min.cells=1)
seur.h8  <- CreateSeuratObject(mat.hu8, project="Hu_Thymus_NKT_8", min.cells=1)
seur.h12 <- CreateSeuratObject(mat.hu12, project="Hu_Thymus_NKT_12", min.cells=1)

# Combine into one seurat object
seur.combined <- merge(seur.h5, y=c(seur.h8,seur.h12), add.cell.ids=c('Hu5', 'Hu8', 'Hu12'), project="HuNKT") # 2661 cells and 18,520 features
print(seur.combined)
```


```{r quality-control}
# QC
seur.combined[["percent.mt"]] <- PercentageFeatureSet(seur.combined, pattern = "^MT\\.")
head(seur.combined@meta.data, 5)
FeatureScatter(seur.combined, feature1 = "nCount_RNA", feature2 = "percent.mt")
FeatureScatter(seur.combined, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
VlnPlot(seur.combined, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, pt.size=.01)
# ggsave(file.path(path.plots, "hu_qc.jpeg"), width=10, height=6)
seur.combined <- subset(seur.combined, subset = nFeature_RNA >= 500 & nFeature_RNA < 4000 & nCount_RNA >=500 & percent.mt < 25)
table(seur.combined@meta.data$orig.ident) # 399 cells hu5; 1828 cells hu8; 331 cells hu12

# See number of cells and features post-processing
print(seur.combined)
```




## 3. SCTransform and Harmony

Code combining SCTransform and Harmony based on this [forum discussion](https://github.com/immunogenomics/harmony/issues/41) and this [seurat tutorial](https://htmlpreview.github.io/?https://github.com/satijalab/seurat.wrappers/blob/master/docs/harmony.html)

```{r SCTransform-Harmony}
# Normalize with SCTransform and find variable features
seur.list <- SplitObject(seur.combined, split.by = "orig.ident")
seur.list <- lapply(X = seur.list, FUN = SCTransform) # weird, SCTransform adds features?!
sct.hvg   <- SelectIntegrationFeatures(object.list = seur.list, nfeatures = 2000)

# Merge back seurat objects to run Harmony afterwards
seur.SCT <- merge(seur.list$Hu_Thymus_NKT_5, y = c(seur.list$Hu_Thymus_NKT_8, seur.list$Hu_Thymus_NKT_12),
                      project = "HuNKT", merge.data = TRUE) # weird, now there are 30596 genes
VariableFeatures(seur.SCT) <- sct.hvg


# Run PCA (don't scale data when using SCTransform)
seur.SCT <- RunPCA(object = seur.SCT, assay = "SCT", npcs = 50)
DimPlot(seur.SCT, reduction = "pca", group.by = "orig.ident")
ElbowPlot(seur.SCT)


# Run Harmony for integration
seur.harmony <- RunHarmony(object = seur.SCT,
                           assay.use = "SCT",
                           reduction = "pca",
                           dims.use = 1:50,
                           group.by.vars = "orig.ident",
                           plot_convergence = F) # converged only after 2 iterations
seur.harmony <- RunUMAP(object = seur.harmony, assay = "SCT", reduction = "harmony", dims = 1:30)
seur.harmony <- FindNeighbors(object = seur.harmony, assay = "SCT", reduction = "harmony", dims = 1:30) %>%
  FindClusters(resolution = 0.8)


# First glance at UMAP
DimPlot(seur.harmony, pt.size = 0.1, label = T, label.size = 7) + ggtitle("SCTransform+Harmony") + theme(legend.position="none")
```


```{r SCTransform-Harmony-plot}
# Display UMAP
p1 <- DimPlot(seur.harmony, group.by = c("orig.ident"), pt.size = 0.1, label = F) + theme(legend.position="top", title = element_text(size=0))
p2 <- DimPlot(seur.harmony, pt.size = 0.1, label = TRUE) + labs(title="Integrated (2558 cells)") + theme(legend.position="none")
p3 <- DimPlot(seur.harmony, pt.size = 0.1, split.by = "orig.ident", ncol = 3)
ggdraw()+
  draw_plot(p1, x=0, y=0, width=.25, height=1)+
  draw_plot(p2, x=.25, y=0, width=.25, height=1)+
  draw_plot(p3, x=.5, y=0, width=.5, height=1)
```




## 4. LogNormalize and MNN

This workflow is the same used for the mouse NKT data.

```{r lognormalize-mnn}
# Normalize and find variable features
set.seed(123)
seur.mnn <- NormalizeData(seur.combined) # normalized data is saved in seur.combined[["RNA"]]@data
seur.mnn <- FindVariableFeatures(seur.mnn) # return 2,000 HVGs
# plot variable features with labels
LabelPoints(plot = VariableFeaturePlot(seur.mnn),
            points = head(VariableFeatures(seur.mnn), 10), repel = TRUE)
# ggsave(file.path(path.plots, "hu_hvg.jpeg"), width=8, height=6, bg="white")


# Run integration & dimension reduction
seur.mnn <- RunFastMNN(object.list = SplitObject(seur.mnn, split.by = "orig.ident"), k = 20)
seur.mnn <- RunUMAP(seur.mnn, reduction = "mnn", dims = 1:30)
seur.mnn <- FindNeighbors(seur.mnn, reduction = "mnn", dims = 1:30, compute.SNN = TRUE)
seur.mnn <- FindClusters(seur.mnn, resolution = 0.8)

# First glance at UMAP
DimPlot(seur.mnn, pt.size = 0.1, label = T, label.size = 7) + ggtitle("LogNormalize + fastMNN") + theme(legend.position="none")
```


```{r lognormalize-mnn-plot}
# Display UMAP
# ggsave("~/Downloads/hu_umap.jpeg", width=5, height=5)

p1 <- DimPlot(seur.mnn, group.by = c("orig.ident"), pt.size = 0.1, label = F) + theme(legend.position="top", title = element_text(size=0))
p2 <- DimPlot(seur.mnn, pt.size = 0.1, label = TRUE) + labs(title="Integrated (2558 cells)") + theme(legend.position="none")
p3 <- DimPlot(seur.mnn, pt.size = 0.1, split.by = "orig.ident", ncol = 3)

# jpeg(filename = file.path(path.plots, "hu_umap.jpeg"), width=5000, height=1500, res=300)
ggdraw()+
  draw_plot(p1, x=0, y=0, width=.25, height=1)+
  draw_plot(p2, x=.25, y=0, width=.25, height=1)+
  draw_plot(p3, x=.5, y=0, width=.5, height=1)
```




### 5. Compare methods

```{r merge-metadata}
# Rename cluster columns for merging downstream
head(seur.mnn@meta.data)
colnames(seur.mnn@meta.data)[6] <- "mnn_clusters"
head(seur.harmony@meta.data)
colnames(seur.harmony@meta.data)[8] <- "harmony_clusters"

# Merge the metadata df
metadata <- merge(seur.mnn@meta.data, seur.harmony@meta.data, by=c("row.names", "orig.ident", "nCount_RNA", "nFeature_RNA", "percent.mt"))
rownames(metadata) <- metadata$Row.names
metadata$Row.names <- NULL
head(metadata)

# Replace the metadata df in the seurat objects
seur.mnn@meta.data <- metadata
seur.harmony@meta.data <- metadata

# Sanity checks
DimPlot(seur.mnn, group.by="mnn_clusters", pt.size = 0.1, label = TRUE) + labs(title="LogNorm+MNN") + theme(legend.position="none")
DimPlot(seur.harmony, group.by="harmony_clusters", pt.size = 0.1, label = TRUE) + labs(title="SCT+Harmony") + theme(legend.position="none")
```


```{r cross-plot}
# Check which cluster corresponds to which across methods
mnn1 <- DimPlot(seur.mnn, group.by="mnn_clusters", pt.size = 0.1, label = TRUE) + labs(title="LogNorm+MNN | Clust on MNN") + theme(legend.position="none")
mnn2 <- DimPlot(seur.mnn, group.by="harmony_clusters", pt.size = 0.1, label = TRUE) + labs(title="LogNorm+MNN | Clust on Harmony") + theme(legend.position="none")
harm1 <- DimPlot(seur.harmony, group.by="harmony_clusters", pt.size = 0.1, label = TRUE) + labs(title="SCT+Harmony | Clust on Harmony") + theme(legend.position="none")
harm2 <- DimPlot(seur.harmony, group.by="mnn_clusters", pt.size = 0.1, label = TRUE) + labs(title="SCT+Harmony  | Clust on MNN") + theme(legend.position="none")

ggdraw()+
  draw_plot(mnn1, x=0,  y=.5, width=.5, height=.5)+
  draw_plot(mnn1, x=.5, y=.5, width=.5, height=.5)+
  draw_plot(harm2, x=0, y=0, width=.5, height=.5) +
  draw_plot(harm1, x=.5, y=0, width=.5, height=.5)
```



```{r key-genes}
# Function to look at genes of interest
plotFeatBoth <- function(gene){
  mnn <- FeaturePlot(seur.mnn, features=gene) +
    labs(title=gene)
  harm <- FeaturePlot(seur.harmony, features=gene) +
    labs(title=gene)
  # Plot both side-by-side
  mnn | harm
}

# Look at genes of interest
plotFeatBoth("ZBTB16")
plotFeatBoth("EOMES")
plotFeatBoth("GZMK")
plotFeatBoth("CCR7")
plotFeatBoth("CCR9")
plotFeatBoth("SELL")
plotFeatBoth("PLAC8")
plotFeatBoth("CD69")
plotFeatBoth("CD4")

# mouse markers?
plotFeatBoth("EGR2")
plotFeatBoth("SLAMF1")
plotFeatBoth("CD44")
plotFeatBoth("NKG7")
plotFeatBoth("KLRB1")
```

