---
title: "Genes of interest PBMCs"
output: html_notebook
---

# 1.IMPORT

## 1.1.librairies
```{r import-library}
library(Seurat)
library(ggplot2)
library(cowplot)
library(scico)
library(tidyverse)
setwd("~/Projects/HumanThymusProject/")

source("./scripts-final/colors_universal.R")
path.volume <- "/Volumes/CrucialX8/Projects/HumanThymusProject/data/human-PBMC/HumanData_29_GenesOnPBMCLineages"
```

## 1.2. data
```{r import-data}
seur.cd4  <- readRDS(file.path(path.volume, "blood.CD4_03_16_23.RDS"))
seur.cd8  <- readRDS(file.path(path.volume, "blood.CD8_03_16_23.RDS"))
seur.gdt  <- readRDS(file.path(path.volume, "blood.GD_03_16_23.RDS"))
seur.mait <- readRDS(file.path(path.volume, "blood.MAIT_03_16_23.RDS"))
seur.nkt  <- readRDS(file.path(path.volume, "blood.NKT_03_16_23.RDS"))

seur.list <- list("cd4"=seur.cd4,
                  "cd8"=seur.cd8,
                  "gdt"=seur.gdt,
                  "mait"=seur.mait,
                  "nkt"=seur.nkt)

colors.list <- list("cd4"=cols_pbmc_cd4,
                    "cd8"=cols_pbmc_cd8,
                    "gdt"=cols_pbmc_gdt,
                    "mait"=cols_pbmc_mait,
                    "nkt"=cols_pbmc_nkt)
```

```{r data-check}
for(i in names(seur.list)){
  seur <- seur.list[[i]]
  show(DimPlot(seur, label=T) + labs(title=i) + scale_color_manual(values=colors.list[[i]]))
}
```




# 2. PLOT GENES OF INTEREST

```{r, fig.width=40, fig.height=40, message=FALSE}
genes_maxexpresssion <- list("ZBTB16"=3.5,
                             "FOS"=5.5,
                             "JUN"=5.5,
                             "EOMES"=4,
                             "GZMK"=4.5,
                             "GZMB"=4,
                             "GZMA"=4.5,
                             "GZMH"=4.5,
                             "GNLY"=5.5,
                             "KLRB1"=5,
                             "IFNG"=4.5,
                             "CX3CR1"=4)


plist_massive <- list()
for(gene in names(genes_maxexpresssion)){
  print("--------")
  print(gene)
  # get row of plots (for one gene)
  plist   <- list()
  plegend <- NULL
  for(i_seur in names(seur.list)){
    p <- NULL
    print(i_seur)
    seur <- seur.list[[i_seur]]
    # make plot
    legendpos <- "none"
    p <- SCpubr::do_FeaturePlot(seur,  features=gene, ncol=1, legend.position=legendpos, border.size=1, pt.size=2, order=T, plot.title="") +
      theme(plot.background = element_rect(color = "black", linewidth = 2), plot.margin=unit(c(0,5.5,0,5.5), "points")) &
      scale_colour_scico(palette = "lapaz", alpha = 0.8, direction = -1, limits=c(0,genes_maxexpresssion[[gene]]))
    p <- ggrastr::rasterise(p, layers="Point", dpi=300)
    
    # add legend once
    if(i_seur=="nkt"){
      plegend <- ggpubr::get_legend(
        SCpubr::do_FeaturePlot(seur,  features=gene, ncol=1, legend.position="right", border.size=1, pt.size=2, order=T)+
          theme(plot.background = element_rect(color = "black"))&
          scale_colour_scico(palette = "lapaz", alpha = 0.8, direction = -1, limits=c(0,genes_maxexpresssion[[gene]]))
      )
    }
    plist[[i_seur]] <- p
  }
  # after looping through lineages, add gene color legend on right
  prow_gene     <- cowplot::plot_grid(plotlist=plist, nrow=1, scale=0.9)
  prow_with_legend <- cowplot::plot_grid(prow_gene, ggpubr::as_ggplot(plegend), ncol=2, rel_widths = c(5, .5), scale=c(0.95, 1), align="v")
  plist_massive[[gene]] <- prow_with_legend
}

# combine all genes
cowplot::plot_grid(plotlist=plist_massive, ncol=1, align="h")

ggsave("~/Projects/HumanThymusProject/scripts-in-progress/human-PBMC/HumanData_29_GenesOnPBMCLineages/plots/combined_umaps_genes2.pdf", width=25, height=55,
       limitsize=F, dpi=80)

```

