---
title: "Human T cell data - Integrate with Park data"
output:
  html_document:
    df_print: paged
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

## 1. IMPORT

### 1.1. Import librairies
```{r import-librairies, message=FALSE}
library(ggplot2)
library(Seurat)
library(ggVennDiagram)
```
### 1.2. Import data - Gapin
```{r import-data, fig.height=8, fig.width=8}
# Import seurat object (generated by annotate-final-seurat.Rmd)
seur.gapin <- readRDS("data/human-thymus/annotation/gapin_full_seu_gene_names_updated_anno.rds") 

# Sanity check
print(seur.gapin) # 78,607 cells
SCpubr::do_DimPlot(seur.gapin, 
                   group.by = "cell_clusters",
                   label=TRUE,
                   label.color="black",
                   legend.position = "none",
                   repel=TRUE,
                   font.size = 24)
# ggsave("data/human-thymus/HumanData_16_ParkIntegration/gapin_umap.jpeg",
# width=10, height=8)
```


### 1.3. Import data - Park
```{r import-park, fig.height=8, fig.width=8}
# generated y annotate-park-seurat.Rmd
seur.park <- readRDS('data/human-thymus/annotation/park_full_seu_gene_names_updated_anno.rds')

# Sanity check
SCpubr::do_DimPlot(seur.park,
                   group.by = "cell_type",
                   label=TRUE,
                   label.color="black",
                   legend.position = "none",
                   repel=TRUE,
                   font.size = 24)
table(seur.park$cell_type, useNA="ifany")
```
## 2. INTEGRATE

### 2.1 Check overlap
```{r fullpark-gapin-integration2}
## KEEP ONLY COMMON GENES TO 2 DATASETS ####
# check out overlap gene names between Park data and our data
ggVennDiagram(
  x=list(rownames(seur.gapin), rownames(seur.park)),
  category.names = c("Gapin" , "Park"),
  label_alpha=0,
  label="count"
) +
  ggplot2::scale_fill_gradient(low="white",high = "blue")

# keep only genes common to the 2 datasets
common_genes <- intersect(rownames(seur.gapin), rownames(seur.park))
length(common_genes) # 13,988 genes
seur.gapin <- seur.gapin[common_genes,]
seur.park <- seur.park[common_genes,]
```

### 2.2 Combine and sanity check
```{r}
seur.combined <- merge(seur.gapin, seur.park)

seur.combined@meta.data <- seur.combined@meta.data %>%
  mutate(subset_annotations = case_when(is.na(subset_annotations) ~ Anno_level_5,
                                        TRUE ~ subset_annotations))      

# Sanity checks
sum(ncol(seur.gapin), ncol(seur.park)) # sanity check number of cells
seur.gapin@assays[["RNA"]]@data[5:10,1:5]
seur.combined@assays[["RNA"]]@data[5:10,1:5]
seur.park@assays[["RNA"]]@data[5:10,1:5]
seur.combined@assays[["RNA"]]@data[5:10,78608:78613] # same data counts

table(seur.combined@meta.data$tissue, useNA="ifany")
table(seur.combined@meta.data$study, useNA="ifany")
table(seur.combined@meta.data$cell_clusters, useNA="ifany")
table(seur.combined@meta.data$Batch, useNA="ifany")
table(seur.combined@meta.data$Anno_level_1, useNA="ifany")
table(seur.combined@meta.data$Anno_level_2, useNA="ifany")
table(seur.combined@meta.data$Anno_level_3, useNA="ifany")
table(seur.combined@meta.data$Anno_level_4, useNA="ifany")
table(seur.combined@meta.data$Anno_level_5, useNA="ifany")

# Save seurat object
saveRDS(seur.combined, "data/human-thymus/HumanData_16_ParkIntegration/seurat_integrated_fullpark_fullgapin.rds")
```

### 2.3 Extract metadata
```{r}
metadata <- seur.combined@meta.data %>% 
  rownames_to_column("barcode_sample") %>%
  as_tibble %>%
  select(barcode_sample, Anno_level_3, Anno_level_4, study) %>%
  mutate(cell_type=case_when(study == "gapin_data" ~ Anno_level_4,
                             TRUE ~ Anno_level_3)) %>%
  select(barcode_sample, cell_type)

write_delim(metadata, "data/human-thymus/HumanData_16_ParkIntegration/metadata.tsv",
            delim="\t")
```

